### ISSUE TITLE
Can't watch replay

### ISSUE THREAD

**Issue by Wrascon** [HearthSim/HSReplay.net#100]
I see only a white screen with the right menu, which does not have full functionality and some simple buttons are not pressed.
![74b553001d884cceb935b7463afe64d9 1](https://cloud.githubusercontent.com/assets/17739216/19744349/da16089e-9bd5-11e6-85ea-525d1d525e21.png)
I can only press the "Show deck" and "Download XML". Sontrols and delete replays are off active. Replay itself does not show. Bottom blank line under the comments. The only place where I can visually watch at least some information on the replay - it "My Replays". But going to have all the rest does not play in any of the browsers, none of my friends.

**Comment by jleclanche** [comment]
Thanks for the report. Are you using an adblocker? A privacy extension like PrivacyBadger?  We've had reports of the domain `joust.hearthsim.net` (which serves the javascript for the replayer) getting blocked by those. Can you try disabling them if you have any?

If that's still a problem, I need some more info:

1. Which browser are you using?
2. What's your country and ISP?
3. What happens when you visit [this page](https://joust.hearthsim.net/) and [this one](https://joust.hearthsim.net/branches/master/joust.js)?
3. You say "none of my friends"; do you mean you know other people affected by this? Similar steps for them, too.

**Comment by jleclanche** [comment]
Note to self: We should move joust.hearthsim to joust.hsreplay; it should at the very least limit the eagerness of addons to block it.

**Comment by Wrascon** [comment]
1. Chrome last version 54.0.2840.71 m (64-bit)
2. Russian, ISP NetByNet.
3. Both pages say "Unable access the site. Timeout response from the website" 
4. I do not know. My friends, too, could not watch it

I tried to do it in Opera. Version 41.0.2353.46 also did not opens
But if i enabled VPN on Opera:
1) I see this 
![aae87406f84f4997ae20cb92c52c2164 1](https://cloud.githubusercontent.com/assets/17739216/19745738/bb74d126-9bdb-11e6-973d-89567df0a736.png)
2) And something like this
![7094b3e0bcc64d3b89be5b711a40aaed 1](https://cloud.githubusercontent.com/assets/17739216/19745788/f532564a-9bdb-11e6-8dfb-df1c720e7923.png)

I came to the conclusion that only works with VPN for me. Problem has been solved, but partially. I hope this information will help you

**Comment by jleclanche** [comment]
I see. We've also had reports of the bucket being blocked in Russia. I'd really love to understand why (I wonder if it's because of the https/cloudflare setup?)... regardless, we'll try to figure this out.

Refs HearthSim/server-provisioning#50

**Comment by jleclanche** [comment]
Keeping this open, we want to make sure this doesnt happen.

**Comment by beheh** [comment]
We're showing a better error whenever this happens nowadays.

**Comment by Hummuna** [comment]
So I have the same exact error, My ISP is Time warner, located in Cincinnati Ohio. I have set my DNS to 8.8.8.8 and even tried 1.1.1.1 . Running Chrome, Internet Explorer doesn't matter. No ad blocker.  Almost 2 years after this post and I have not seen any other comments on this error except this forum

**Comment by jleclanche** [comment]
@Hummuna Can you include a screenshot of the page? Also, a screenshot of the devtools console (Ctrl+Shift+i => Console)

**Comment by Hummuna** [comment]
![hs_error_console](https://user-images.githubusercontent.com/40130792/41203769-a65fcc14-6ca9-11e8-9d64-95585ef725da.jpg)

**Comment by jleclanche** [comment]
@Hummuna Can you load this file?

https://s3.amazonaws.com/joust.hearthsim.net/branches/master/joust.js

**Comment by Hummuna** [comment]
![refused](https://user-images.githubusercontent.com/40130792/41203848-e91a51a4-6caa-11e8-9ea3-fec239f6ff8d.jpg)

**Comment by jleclanche** [comment]
So that sounds like a problem with your internet. Maybe your ISP is blocking it, or your country, or your antivirus/firewall/system administrator.

**Comment by Hummuna** [comment]
So I did a tracert and looks like there is a host file entry. Maybe from pirate patch for some software. 

Let me try and remove it and see if it helps. Hopefully this helps someone in the future.

![tracert](https://user-images.githubusercontent.com/40130792/41203924-cfd9ff5e-6cab-11e8-836a-40ed635cfebd.jpg)

**Comment by jleclanche** [comment]
Could be an overzealous adblocker.

**Comment by Hummuna** [comment]
bingo from a pirate patch for Adobe softeware or something. It is in my host files.

So for FUTURE people having issues theck your host file under

C:\Windows\System32\Dirvers\Etc\Hosts

See if you have an entry for 127.0.0.1    s3.amazonsws.com
![hosts](https://user-images.githubusercontent.com/40130792/41203956-5944b734-6cac-11e8-82fb-1abb708a8774.jpg)

**Comment by Hummuna** [comment]
It works now!!
![works](https://user-images.githubusercontent.com/40130792/41203972-a1e260e0-6cac-11e8-89a5-5bbb38dd3689.jpg)
