### ISSUE TITLE
Global game: Real ID players / UNKNOWN HUMAN PLAYER not stringified

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#101]
e.g. https://hsreplay.net/replay/WKskiBMa8CRwqG6mjYfJRT reads "vs. Rai"

**Comment by jleclanche** [comment]
I want to get rid of RealID names. Now that we have the PegasusAccount model we can do that more easily.

**Comment by jleclanche** [comment]
This is fixed
