### ISSUE TITLE
My replays page not showing rank for each game

### ISSUE THREAD

**Issue by Ahrimourn** [HearthSim/HSReplay.net#1012]
I noticed the mode column in my replays has changed to mostly just display 'ranked' for the most part.  The odd time it will show the current rank, but that is infrequent and sporadic.

Was that an intentional change?  I have tried different browsers just to rule out cookie issues.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/41544875/47606537-a7737c80-d9e2-11e8-8802-5c26d8a59641.png">

**Comment by azeier** [comment]
What deck tracker are you using and which version are you on?

**Comment by Ahrimourn** [comment]
Sorry I should have mentioned and thought of that - its the HSTracker for Mac, version 1.5.1c

**Comment by azeier** [comment]
This is an issue with HSTracker, it's probably failing to get the correct game metadata since the latest Hearthstone update. I'll move this issue over there.

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSTracker #1008](https://github.com/HearthSim/HSTracker/issues/1008) via [**ZenHub**](https://www.zenhub.com/)
