### ISSUE TITLE
Hide opponent hand

### ISSUE THREAD

**Issue by bmichotte** [HearthSim/HSReplay.net#102]
It could be nice to add an option (checkbox) to hide the hand of your opponent to add some suspense. 
Also, this option should be added to share links

**Comment by jleclanche** [comment]
It's already possible. You can disable the card Oracle at the bottom right.

**Comment by jleclanche** [comment]
Closing - won't add the option to the shared links and the main feature is already done.

**Comment by beheh** [comment]
It's not used anywhere, but we actually *do* support this setting in the url - just append `#reveal=0` to hide the cards (or `&reveal=0` if you already have a turn linked).
