### ISSUE TITLE
Login /Uploading Collection not possible

### ISSUE THREAD

**Issue by Vortilion** [HearthSim/HSReplay.net#1030]
Hi, 

uploading a collection and login in via deck tracker-app on windows is not possible. There seems to be a developer url in the configuration cause if I try to log in it tries to open the url "https://localhost:17782/?code=XXX". Looks to me as if a developer left a localhost testing url in the config... Also if I click on the big "Collection uploading" it tries to open a localhost-URL...

**Comment by jleclanche** [comment]
You need to allow HDT to open a web server on those ports. That localhost url is important to the authentication flow and will redirect to hsreplay.net in the end.

This is the wrong issue tracker btw, there's an HDT issue tracker on GitHub.

**Comment by Vortilion** [comment]
Uhm, ok, how do I do that? HDT has access to the internet, I also tried to allow it explicity in the windows firewall. All I'm getting is **ERR_CONNECTION_REFUSED**.

Also, where do I find the HDT issue tracker? The onlx github I found on your site in the help section is this one...

**Comment by Vortilion** [comment]
Ah, found it. Sorry for posting in the wrong section.
