### ISSUE TITLE
how to share all of my reocrds to my friend

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HSReplay.net#106]
my replays  url is https://hsreplay.net/games/mine/#
single record url like this https://hsreplay.net/replay/hXxa9ZUJvbstHkYE2EoYXC

but how can I share my records to my friend?even if  my friend do not have an account for this website

**Comment by chucklu** [comment]
any idea?

**Comment by jleclanche** [comment]
You can't, yet - We're planning to do playlists so you can easily share a list of games, but we're short on time and focusing on a couple of other issues right now.

**Comment by jleclanche** [comment]
Dup of #66
