### ISSUE TITLE
language setting for those who do not have an account

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HSReplay.net#107]
I can set the card language when I log in .
but when I share the record with my friend,the card language is English by default
there is no place for him to set language of the card

**Comment by jleclanche** [comment]
We're planning to make a language setting available from the replayer itself (it'll show up in the bottom right of the replayer, next to fullscreen).

@beheh what's the status on that? Were we blocked on something?

**Comment by chucklu** [comment]
excellent, waiting for that

**Comment by beheh** [comment]
Not blocked, just have to squeeze some time in.

**Comment by beheh** [comment]
Tracking at HearthSim/Joust#183.

**Comment by beheh** [comment]
This has now been landed and will be deployed shortly. The selected preference in the replay applet will always have priority over the account-wide setting, but we default to that if the user has not selected a language in the applet yet.
