### ISSUE TITLE
Spell Damage not updated correctly

### ISSUE THREAD

**Issue by BVA64** [HearthSim/HSReplay.net#109]
https://hsreplay.net/replay/vCazg7aauxoGzGghTUXYQU#turn=7a

Maelestrom Portal shows 2 damage even after Wrath of Air Totem is summoned (Azure Drake already in play).
After Azure Drake is killed it still shows 2 damage. (turn 8)
When I jump back to the second half of turn 7 damage is shown correctly as 3.

**Comment by beheh** [comment]
Issue moved to [HearthSim/Joust #182](https://github.com/HearthSim/Joust/issues/182) via [**ZenHub**](https://www.zenhub.com/)

**Comment by beheh** [comment]
Thanks for your report, this has been fixed and will be deployed shortly.
