### ISSUE TITLE
Fallback URL for Joust

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#114]
@beheh Regarding Russia, I've been working on this further the past couple of days and I think our best bet is to have a fallback for Joust that loads it from the source URL if it's not available from the "generic" hearthsim cdn.

That is: https://s3.amazonaws.com/joust.hearthsim.net/branches/master/joust.js

**Comment by beheh** [comment]
Ther's no inbuilt way to do that, I'll have to write some surrounding code to dynaimcally load the other URL, similar to what the front page does.

**Comment by azeier** [comment]
This is done iirc?

**Comment by jleclanche** [comment]
It's not, we just disabled cloudflare. I'd like to reenable it at some point...

**Comment by jleclanche** [comment]
Closing, won't do this. We'll move to use joust off npm instead.
