### ISSUE TITLE
The tooltip for the classes played chart incorrectly says 'Victory Chart'

### ISSUE THREAD

**Issue by riQQ** [HearthSim/HSReplay.net#118]
Firefox 50.1
![chart](https://cloud.githubusercontent.com/assets/3404787/21740550/e9018142-d4bc-11e6-801f-9c4526a9af6d.png)

**Comment by azeier** [comment]
Where exactly and with what browser do you get that tooltip? I can't seem to get that to happen.

**Comment by riQQ** [comment]
Added the information to the OP.
