### ISSUE TITLE
Auth Token API inconsistent response on missing access token header 

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#122]
When requesting `https://api.hsreplay.net/v1/tokens/:authtoken:/` with only the header `X-Api-Key: :apikey:` for a claimed auth token I receive the following response:

```json
{
"key":"587f7502-d992-46bd-aab8-...",
"user":{"id":5,"battletag":null,"username":null},
"test_data":false
}
```

Notice the user object having an ID, but an ommited battletag and username.

If I add `Authorization: Token :authtoken:`, I receive the correct respose:

```json
{
"key":"587f7502-d992-46bd-aab8-...",
"user":{"id":5,"battletag":"BehEh","username":"BehEh#1337"},
"test_data":false
}
```

These responses should not differ.

**Comment by jleclanche** [comment]
Yes, this is correct.
