### ISSUE TITLE
Add a way for users to revoke access tokens

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#123]
Users should be able to revoke access tokens, e.g. if they don't use the account any more, or if they accidentally published them.

**Comment by jleclanche** [comment]
I've explicitly not added a way because doing so is irreversible and hard to handle on the deck tracker side.

**Comment by beheh** [comment]
We should obviously warn users. It's no different than removing an authorised computer on your Google or Facebook account. Deck Trackers *should* request a new token if it's definitively missing (404 as opposed to timing out or server error).

**Comment by jleclanche** [comment]
I think we just won't do this until we switch to an oauth system.
