### ISSUE TITLE
Run selenium tests in the pipeline on dev server

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#141]
Make smoke tests also run against dev.hsreplay.net in the middle of the deployment pipeline to protect faulty code from propagating to production.

**Comment by amw2104** [comment]
What I'm imagining is:
1) Code is deployed to dev.hsreplay.net and that server is restarted.
2) Full smoke test suite is run against dev.hsreplay.net
3) If it passes then the code starts propagating out to the production web servers. If it fails then we reset the latest symlink on dev.hsreplay.net to the previous stable build.

**Comment by jleclanche** [comment]
This issue is outdated with the new deploy system. When we do this we'll do it against the staging cluster.
