### ISSUE TITLE
Code review changes to server provisioning to setup smoke tests

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#142]
I couldn't get this running locally, or figure out what triggers the ci_settings.py files get regenerated so I'd like to code-review these changes with you to make sure this is all working code:

https://github.com/HearthSim/server-provisioning/commit/f486fa24c81ab9bdf9d9cdca3dc255501771c275

**Comment by jleclanche** [comment]
The build server's ansible file is not usable at the moment. We can spend some time getting it to work.
