### ISSUE TITLE
Finish discover choices widget on card details

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#143]

**Comment by azeier** [comment]
Should be working, 202-ing at the moment

**Comment by azeier** [comment]
@amw2104 still only returning 202: https://hsreplay.net/analytics/query/single_card_choices_by_winrate?card_id=2895&GameType=RANKED_STANDARD (Dark Peddler)

**Comment by amw2104** [comment]
Fixed.

**Comment by amw2104** [comment]
Still needs win rate to get displayed in the UI
