### ISSUE TITLE
Add joust-style window frames to hero portrait on deck details

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#147]

**Comment by jleclanche** [comment]
We can't generate those with Sunwell at the moment.

**Comment by azeier** [comment]
We can do what joust does though. @beheh can you take care of this?

**Comment by beheh** [comment]
Yeah, although it won't work in Internet Explorer/Edge.

**Comment by jleclanche** [comment]
Doesn't seem like we're doing this, and it just doesn't sound like a big deal (current art is fine)
