### ISSUE TITLE
Capture an influx metric everytime the premium modal is presented

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#155]
Include:
	- a Tag: is_anonymous_user
	- a Tag: is_returning_from_battlenet

**Comment by beheh** [comment]
We're now reporting this to GA, Influx will follow soon.

**Comment by jleclanche** [comment]
We don't need it in both (and I'd rather not have it in both) as long as we can find and follow it in one.

**Comment by beheh** [comment]
@jleclanche Then this is done?
