### ISSUE TITLE
Bonus chart: Visualize deck winrate over time vs opponent class

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#168]

**Comment by azeier** [comment]
@amw2104 Getting a 500 for this query: https://hsreplay.net/analytics/query/single_deck_winrate_vs_opponent_class_over_time?deck_id=109898692&GameType=RANKED_STANDARD

**Comment by amw2104** [comment]
Fixed.

**Comment by azeier** [comment]
Depends on #187

**Comment by azeier** [comment]
Depends on #235 and #236
