### ISSUE TITLE
Write tutorial bubbles

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#180]

**Comment by azeier** [comment]
We should make them not-active by default and instead have an alert at the top of the page that let's you "start the tutorial" or dismiss it, without having a popup everywhere.

**Comment by beheh** [comment]
It will only ever show once per page, I think even a simple button will be overlooked pretty often. It's also very easy to dismiss it. I do want a button to retrigger it at later times though.

**Comment by azeier** [comment]
One popup per page you **have** to deal with before being able to interact with it is very obnoxious. If the cookie can't be saved, that gets even worse. A dismissable alert over the entire content (see 1000 decks message) gets the same job done without being so in your face. 

Agreed on the retrigger button.

**Comment by beheh** [comment]
Getting the no-cookies argument out of the way early, if you don't allow cookies or local storage you have a lot more problems on the page, for example by blocking for the download and JSON parsing of the full 3/4 MB hearthstonejson db on every page call - we don't even display content until it's ready on the stats pages, right?

The thing is, we might be used to instantly understanding it, since we're used to the layout and we're quite technically literate. You have to imagine a lot of the first-time visitors have never even interacted with our UI before or are not very technically literate and might be very overwhelmed by all the UI, so a small "Tour" button is the last thing they'd find.
The introduction is useful even if you open a subpage from an external link - you're just introduced to the specific page with specific filter presets instead of the generic no-filters view.
We can even make the tours themselves more modular, so some of the concepts, like the sidebar filters are only explained once cross-site.

This is not a "We would like to save cookies on your computer" popup, this is a warm "Hi there, we're here to help and you can expect detailed explanations from us wherever you are". Note that the bubbles don't every stop you from interacting with the page! We could probably drop the introductory bubble though.

Note that the specific messages are just a draft for now - feel free to rewrite them or add them to further pages if you want.

**Comment by azeier** [comment]
> Note that the bubbles don't every stop you from interacting with the page! 

![tour](https://cloud.githubusercontent.com/assets/7737910/23578407/7ece5cc8-00d6-11e7-8d5e-ffe0e1bb667c.PNG)

This does completely stop me from interacting with the page. I have zero choice but to deal with it immediately.

**Comment by beheh** [comment]
Your nitpicking a very specific example here, assuming that a visitor knows exactly where to look for the Azure Drake inclusion rate. You cannot forget that we have an *extremely* skewed perspective, having developed the UI ourselves - we know exactly where to look, and that's we personally might get annoyed. People seeing the popup will most likely never have seen the page before and will be very happy about some guidance.

Like I said, we could probably remove the central popup though and start with the attached ones, like the ones at the filters so at least the central content isn't blocked.

We can obviously do a feature detection for cookies with JS, but I doubt it's worth it. In the end I'd rather have the [**0.2%** of users with first-party cookies disabled](https://blog.yell.com/2016/04/just-many-web-users-disable-cookies-javascript/) click the tour away repeatedly rather than increasing our bounce rate by any single point.

**Comment by jleclanche** [comment]
@beheh the tutorial popups are extremely obnoxious at the moment, and few people are actually going to need them. It's good we have it, but they shouldn't be on by default.

**Comment by beheh** [comment]
The system is ready, just need to add them to pages in a way so everyone is happy.
