### ISSUE TITLE
Add overload and poisonous filters to card db

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#183]
We need overload in hearthstonejson

**Comment by azeier** [comment]
Also discover

**Comment by jleclanche** [comment]
There will be no changes in hearthstonejson for this.

**Comment by jleclanche** [comment]
I'll be adding the referenced tags separately. WIP.

**Comment by jleclanche** [comment]
All done on my side.

**Comment by azeier** [comment]
All done.
