### ISSUE TITLE
Make it more obvious that table columns are sortable

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#188]
In deck details and deck list views.

**Comment by amw2104** [comment]
In a feedback session tonight, RayC was also confused about what the table was sorted by and then how to tell which one was sorted. I think maybe just making the sort indicator larger would solve it.

**Comment by beheh** [comment]
I've pushed a commit to fix our generic component, SortableTable. The deck lists are not using that yet, though.
