### ISSUE TITLE
Switch to staging/stable branches for all autodeployed projects

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#20]
We want separate branches so we can push to `master` without breaking the live site.

- [ ] hsreplaynet
- [ ] Joust
- [ ] other projects?

What about naming (should be consistent across all our projects)? `staging`/`live`, `staging`/`production`, `test`/`stable`...

**Comment by jleclanche** [comment]
Moved to https://github.com/HearthSim/server-provisioning/issues/8
