### ISSUE TITLE
Rework cancel account page

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#217]
- Prevent account delete requests if you have subscriptions running and not cancelling at end of period. Be verbose about why and give a link to the billing page.
- Add a required "Reason" radio field. One of those fields should be "Logged in with the wrong Battle.net account", so that we can interrupt the flow and follow up on those directly so people don't lose their replays.
- Improve post-delete flow. Maybe a post-delete landing page.

**Comment by jleclanche** [comment]
First and most important item is done. Rest can wait.

**Comment by beheh** [comment]
Tracking elsewhere.
