### ISSUE TITLE
Add "Last Updated" Watermark or Info field to pages

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#222]
I'll start adding the timestamp to the datasets. The "?" Info icon text will read:

"We try to keep the data as up to date as possible. Pages get updated as fresh data becomes available."

For personalized stats for free users, we'll add the sentence:

"Personalized Stats For Free Accounts Update Weekly"

**Comment by amw2104** [comment]
All result sets now have an "as_of" timestamp property, which shows when the data set was generated.

**Comment by azeier** [comment]
Added timestamps with https://github.com/HearthSim/HSReplay.net/commit/bc2ee42561f7eb27631bba0fd26d7dd6d1b65dab, still needs the info text.
