### ISSUE TITLE
Both players losing gets marked as 'unknown result'

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/HSReplay.net#228]
It might not necessarily be an issue within HSReplay, but the problem is shown there.

When both heroes go to 0 health (or below) at the same time, HSReplay marks that game with 'unknown' as result.
This [replay*](https://hsreplay.net/replay/fXyo9xdypjWVrf2dNYdVnN) is an example of that scenario.

It might be related to #110 since a third state for property `won` could be introduced.
The other possibility is generalizing the third state into a loss.

*[Another replay](https://hsreplay.net/replay/52DAjdgkh2atEqa6h2LLk6)

**Comment by jleclanche** [comment]
Is this only in the replay itself or also in the replay list?

**Comment by Bert-Proesmans** [comment]
I suppose you mean during the replay as "in the replay".
'Unknown' result is only shown in the replay list, see ![the screenshot](https://anonimag.es/i/replay-list8fbac.png)

During the replay, when all turns are over and both heroes die. There is no overlay shown with the text "[PLAYER] Lost" (or equivalent "Won").
