### ISSUE TITLE
Use If-Modified-Since header to reduce load on server

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#234]
All the redshift datasets now always respond with a "last-modified" header which is the same timestamp as the "as_of" field within the response body. If the client stores these and then sends an If-Modified-Since header it will allow the server to respond with a 304 Not Modified whenever possible and reduce server load by quite a bit.

Implementing this is important, especially on queries like mulligan guide by class, since some of the global queries marshal large datasets into memory for filtering.

**Comment by beheh** [comment]
Can do, but shouldn't that be happening between HSReplay.net <-> Cloudflare anyway?

**Comment by jleclanche** [comment]
I'm pretty sure CF does this for us, yes, but it's worth double checking.

**Comment by beheh** [comment]
I checked, browsers should already be sending this since you're sending Last-Modified. If I test the pages with cache enabled they do indeed load a lot faster, and my console tells me that they are being fetched from disk cache. There's no need to implement this native behaviour in our JS.

**Comment by azeier** [comment]
It doesn't appear to be very consistent for me with chrome.

**Comment by beheh** [comment]
Can you clarify and describe how to reproduce? I've tested Firefox and Chrome and I doubt we're hitting a browser caching bug here. Make sure you're not disabling cache while devtools are open, and are not refreshing with cache-bypass (neither use <kbd>Ctrl</kbd> + <kbd>F5</kbd> nor <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F5</kbd>).

**Comment by amw2104** [comment]
CF does not do this for us unless we setup a "Page Rule" to "Cache Everything" for the /analytics/query/* path prefix, however this will invalidate our ability to restrict which users can access which queries. I confirmed that the browser is already doing this for us.
