### ISSUE TITLE
Add multi series support for chart tooltips

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#236]
The current ones are based on hovering the VictoryArea.

**Comment by beheh** [comment]
Alternatively see if FormidableLabs/victory#504 is fixed and lands anytime soon.

**Comment by azeier** [comment]
I meant tooltips (and indicators) for multiple VictoryLine elements.

**Comment by joolean** [comment]
@beheh @azeier That FormidableLabs fix was merged 5/23. Is this still relevant?

**Comment by azeier** [comment]
Not sure to be honest, but this issue hasn't come up again since a year ago since we didn't build anything relevant. So we can close this for now.

If we end up building some new charts there's a good chance we are just going to use plain d3 anyway.
