### ISSUE TITLE
Add lightbox effect to screenshots on premium landing page

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#243]
- [x] Make subscribe button work on it
- [x] Remove the css-powered english text (`content` rules)
- [x] Remove pricing outside of the modal
- [x] Include some screenshots
- [ ] Add lightbox for screenshots
- [x] Fix btn-group on mobile

**Comment by beheh** [comment]
This should all be done? I guess lightbox screenshots could still be added.

**Comment by joolean** [comment]
Closing: Low urgency.
