### ISSUE TITLE
Create a new DRF Redshift API endpoint

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#245]
Make sure any IP address that starts sending requests too quickly starts getting presented with CAPTCHAs. We believe Cloudflare does this for us, so we just need to run a quick test to confirm our protection is working.

**Comment by jleclanche** [comment]
We'll use DRF.

**Comment by amw2104** [comment]
It is critical that we have some form of tested controllable throttling / rate limiting / anti-scraping protection for the site. Please leave this ticket open until I have confirmed that we have sufficient protection in place.
