### ISSUE TITLE
Make free mode toggle show everything except launch 

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#247]
Make it so that the premium model and the pricing details are all visible when using the "Freemode" toggle. The only thing that should be disabled is actually triggering the Stripe checkout.js. 

The "freemode" toggle is a key tool for our development tool chain. We must be able to use it to see all aspects of our customers experience in order to be able to effectively continue to evolve the site.

If it's possible to even trigger the checkout.js process and just deactivate the "Subscribe" button, that would be even better. But if that's not possible, we should at least be able to get to the point where we can see the premium modal, and see the pricing which our customers see on the premium about page.

**Comment by beheh** [comment]
This is more of a @jleclanche thing, since this means we need to switch serverside or always render a premium modal which he was against.

**Comment by amw2104** [comment]
This is important we get this done. Right now we can't see the experience our customers are having for the "My Cards" page and we can't confirm important things like that we have TOS acceptance language on every purchase path without having to go modify our subscriptions in the stripe dashboard.
