### ISSUE TITLE
Update Checkout description when signing up to a plan

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#248]
In the Checkout form triggered from the modal and the one triggered from the premium landing page, the `data-description` should be updated to the price of the selected plan, like so:

![image](https://cloud.githubusercontent.com/assets/235410/24077075/b2135fce-0c49-11e7-94e7-ac64e0a94abf.png)

**Comment by beheh** [comment]
Work is happening at dev/stripe-tracking.
