### ISSUE TITLE
Review and Finish PegasusAccount Capture

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#252]
In an earlier conversation you mentioned that we were going to need to wipe, reset, and backfill the pegasus account flow before launch because comparing usernames to player names wasn't implemented.

**Comment by jleclanche** [comment]
I'm currently running a three-step PegasusAccount backfill:

1. Update the GlobalGamePlayers with null PA with the following:

```py

def update_pegasus_account(player):
    if player.pegasus_account:
        return player.pegasus_account
    defaults = {"region": BnetRegion.from_account_hi(player.account_hi), "battletag": player.name}
    account, _ = PegasusAccount.objects.get_or_create(account_hi=player.account_hi, account_lo=player.account_lo, defaults=defaults)
    player.pegasus_account = account
    player.save()
    return PegasusAccount.objects.get(pk=player.pegasus_account.pk)


while True:
    if not GlobalGamePlayer.objects.filter(pegasus_account=None).exists():
        break
    for i, player in enumerate(GlobalGamePlayer.objects.filter(pegasus_account=None)[:50000]):
        acc = update_pegasus_account(player)
        print("%i: Set %r to %r" % (i, player, acc))
```

2. Once done, will go through all HSTracker uploads and attempt to identify bad friendly player IDs and correct them, through a custom reprocessing script. Will flag owner users in the process.

3. Once done, will go through all Users and attempt to identify their PAs by looking at the games with PAs matching their names.

**Comment by jleclanche** [comment]
Ok, I'm dropping this from the milestone because the part that was essential for it is *done* (we have enough pegasus accounts in the db that most of the population is covered at this point).

The HSTracker de-crapping is not necessary for launch. But I'm working on it.

**Comment by jleclanche** [comment]
Done.
