### ISSUE TITLE
Verify messaging if Stripe declines/puts payment into review

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#259]
We want to make sure we show the user an appropriate message somewhere after the Stripe dialog has closed and the subscription request form has been sent.

**Comment by jleclanche** [comment]
If the payment is declined on input, the form doesn't close, Checkout already does this.

**Comment by beheh** [comment]
Using a fraudelent card (4100000000000019) the dialog closes successfully, I get redirected and then I get a very short-lived flash at the top of the page, telling me the card has been declined. This is fine, but the flash should probably stick around a little longer and be styled, it's currently blue on blue.

Using a card with elevated risk (4000000000009235) the dialog closes, I get redirected back, no message is given and nothing happens. I can see the subscription appearing in the review queue. I expect users might try to redo it at this point. Testing it locally I got a "you are already subscribed" flash on the second time, even though I was never subscribed (but I guess the other request is in the queue?). We mainly need to improve messaging in this case.

**Comment by beheh** [comment]
I've improved styling a bit. I'll revisit this soon when I port the messages to JS.
