### ISSUE TITLE
Rediscuss page titles

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#260]
## Visual Clutter

With the new page titles we're adding lots of visual clutter if you navigate the site using multiple tabs. Compare these two screenshots (Firefox and Chrome respectively):

![grafik](https://cloud.githubusercontent.com/assets/929769/24370532/0554b3ec-1328-11e7-8a0a-258e2c762295.png)
![grafik](https://cloud.githubusercontent.com/assets/929769/24370557/1e218fd0-1328-11e7-835d-dfbdcb45d09e.png)

We could have a clearer distinction:

![grafik](https://cloud.githubusercontent.com/assets/929769/24371040/dd9012c8-1329-11e7-906c-1cbfd7af2c96.png)
![grafik](https://cloud.githubusercontent.com/assets/929769/24371160/491e0374-132a-11e7-9dc6-9339cc4293df.png)

Browser tend to clip titles after around 20 characters or so in the tabs, so it's a large part is not even visible for any title longer than one or two short words.

Page titles are not required for Google/SEO, since it will append the page/company name by itself.
Social media uses the de-facto standard [OpenGraph](http://ogp.me/), which is specified seperately and can ensure that the brand title appears on social pages.

The potential benefit of having titles is increased brand visiblity in places where the full string is visibile and nothing else, so potentially bookmarks and browser window titles.

## Home title

If users open a link to hsreplay.net in their browser with the intent of checking it out later, they see this:

![grafik](https://cloud.githubusercontent.com/assets/929769/24371104/14819694-132a-11e7-9b4e-18096c471ac6.png)

This completely hides Hearthstone, replays, and our brand name. We previously had "HSReplay.net". If we want a punchline for SEO reasons we could append our subtitle, but I'm more concerned about people not recognising the tab.

## Who else doesn't have brand names in their page titles?
- GitHub
- Reddit
- Discord (Web)

**Comment by jleclanche** [comment]
Both Github and Reddit have breadcrumbs instead of site title.

**Comment by beheh** [comment]
For now I think we should at least swap the homepage title, so that HSReplay.net is first there - can I override the full page title somehow?
