### ISSUE TITLE
Finish Kazakus Potion Power Article

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#261]
We should aim to get this published the day after we launch because it's another high impact reddit post that we can use to drive another wave of traffic to the site, plus all the statistics are about to get invalidated by set rotation, so we should get it out there before that happens.

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/Company-Tracker #88](https://github.com/HearthSim/Company-Tracker/issues/88) via [**ZenHub**](https://www.zenhub.com/)
