### ISSUE TITLE
the replay is currently unsupported 

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HSReplay.net#263]
I found the record of is supported by the website.
I have tried to uploaded the record several times,the record was uploaded successfully  finally.

maybe you should check the wrong info given to the user.
I think,when i can not uploaded the record ,it's the problem of my network.

**Comment by beheh** [comment]
Could you add a link to the replay in question, and any failed uploads?

**Comment by chucklu** [comment]
https://hsreplay.net/replay/UrYXRngZnKqSg2Cym3qSGC
this record uploaded several times @beheh

**Comment by chucklu** [comment]
now, i can not uploaded the record again.
evenif the latest record

I wonder if the server is down?

**Comment by chucklu** [comment]
another uploaded game after trying more than 10 times
https://hsreplay.net/replay/RPWv8VpAL9zGBatHVG4wZ8

**Comment by jleclanche** [comment]
@chucklu Are you getting upload failures on the *site* after upload, or on HDT itself? If the former, can you link the failures?

If the latter, it might just be an issue with your connection. The API is in the US and I see you're in China. You might be simply having trouble to communicate with Amazon servers.

**Comment by chucklu** [comment]
@jleclanche  yes,I am using HDT to upload the game record
so,if upload failed is caused by the network problem.
Could you give me the correct information about the reason of upload failed?
the wrong information I get,make me confused.

**Comment by chucklu** [comment]
Submit a new issue in HDT https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3186
