### ISSUE TITLE
BGT cleanup

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#264]
To do as soon as enums are updated on hdt/hstracker etc: Every game bgt 7 should be changed to 10 instead.

**Comment by beheh** [comment]
This was done eventually?

**Comment by jleclanche** [comment]
Don't think so no, we still have to do the db cleanup.

**Comment by jleclanche** [comment]
```
    min    |    max    
-----------+-----------
 297036559 | 321617059
(1 row)
```

**Comment by jleclanche** [comment]
Done
