### ISSUE TITLE
card language setting support for decks

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HSReplay.net#268]
I  knew  you guys make a great feature about decks from https://hsreplay.net/articles/7/introducing-hsreplaynet-statistics
I hope you can support the language in account setting or support language setting for those who don't have an account.

https://hsreplay.net/decks/
https://hsreplay.net/decks/aoQEFxmStGbNuddan43Xce/#tab=breakdown
the card language in deck is English by default

**Comment by beheh** [comment]
Yes, this is planned!

**Comment by chucklu** [comment]
@beheh Do you have a plan to support multi language for the whole website ui?
Like the articles,trending,decks and the filters

**Comment by beheh** [comment]
It would be nice if we manage that, but that will probably take longer. I expect we'll have language selection for Hearthstone cards/descriptions available soon and full UI translation at a later point in time.

**Comment by jleclanche** [comment]
We can add translations to most of the card stuff fairly easily, but the card images themselves will take longer as there's a lot of text layout issues to fix first.

**Comment by jleclanche** [comment]
Closing, that was actually implemented a while back.
