### ISSUE TITLE
Connect multiple regions with one Battle.net account

### ISSUE THREAD

**Issue by tommyjiang** [HearthSim/HSReplay.net#271]
I would like to know whether `HSReplay.net` support multiple regions with one Battle.net account, such as US, EU and KR etc. I tried to connect multiple regions with one Battle.net account on the `Battle.net` page (https://hsreplay.net/account/social/connections/) but it seems not to be working.

Thanks.

**Comment by jleclanche** [comment]
Your Battle.net account is region-less. You can connect to it with any of them, the region dropdown is mostly there for China which is the only region with separate accounts.

**Comment by tommyjiang** [comment]
@jleclanche Thanks for your reply. I tried to upload replays with `HSTrakcer`, but I am only able to do so when I log in to `US` server with my Battle.net account. In `KR` and `EU` region, I can not upload my replay. Is this related to the `HSTracker` or maybe I should open an issue there? Thanks.

**Comment by jleclanche** [comment]
Yeah that sounds like an hstracker issue. @bmichotte do you know what's happening there?

**Comment by bmichotte** [comment]
For reference : https://github.com/HearthSim/HSTracker/issues/801
