### ISSUE TITLE
PLZZZZZZZ ADD https://disguisedtoast.com site to hearthstone deck tracker import sites

### ISSUE THREAD

**Issue by ZaaaM** [HearthSim/HSReplay.net#279]
PLZZZZZZZ ADD https://disguisedtoast.com site to hearthstone deck tracker import sites

**Comment by azeier** [comment]
Wrong repo.

Please message Toast about it, any website can implement HDT importing on their own: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/RFC-Importing-Implementation
