### ISSUE TITLE
Decks with fewer than 1000 games played still appear

### ISSUE THREAD

**Issue by garyking** [HearthSim/HSReplay.net#280]
In Decks page, choose an Opponent class. Sort by Winrate Descending. Decks with fewer than 1,000 games played appear.

**Comment by azeier** [comment]
Those are still decks with >1000 games. The number shown is the match count against the selected opponent.

**Comment by garyking** [comment]
Is there a minimum for those?

**Comment by azeier** [comment]
The only restriction is 1000 games played, they could theoretically all be against paladin.

**Comment by garyking** [comment]
The lowest number of games played for "X class vs. Druid" is 77 games for a deck. It seems like there's a floor, although you say there is none? So if there's no floor, though, then the sample size for some of these matchups could be ridiculously small like 1 game?

**Comment by azeier** [comment]
If some class sees no play, yes, there could be matchups with 1 game.
