### ISSUE TITLE
Cannot sort by column in deck breakdown section. Neither selecting an opponent class does any effect.

### ISSUE THREAD

**Issue by maikimaiko** [HearthSim/HSReplay.net#282]
Affects any deck breakdown section. For example: https://hsreplay.net/decks/3Gg4mTqkKgPvrronYaNzB/?utm_source=hdt&utm_medium=client.

Tested it only with Chrome.

**Comment by maikimaiko** [comment]
Tested it also in Edge.

**Comment by beheh** [comment]
Can reproduce but I’m on mobile right now, I’ll fix it in a few hours.
