### ISSUE TITLE
Filter replays by particular cards

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#283]
@krzikalla commented on [Tue May 09 2017](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3244)

I am looking for a feature that lists (and thus lets me investigate) only those replays, where a certain card plays a role. Such a feature would be great in order to evaluate the impact of a card.

The filter should contain a field for the card name and some check boxes (maybe a radio button): 
* card mulliganed
* card drawn 
* card played

**Comment by jleclanche** [comment]
Clearly not happening.
