### ISSUE TITLE
Add localized number formatting and use it across the site

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#307]
As a foreign site visitor I want to be able to see numbers in the format I am used to, so that I can understand them.

This work relates to integrating a library to format our numbers in the way foreign visitors expect, so for example using the comma instead of the dot for decimals in German. Note: This doesn't include dates (handled by #783).

For now, we can statically import all the needed locale files at the top of `i18n.ts` (like ICUs `locale-data`) as they are pretty small. We should be able to do something like `import de from "numbro/languages/de-DE"` and then register it in numbro using `numbro.registerLanguage(de)`.

Note: This ticket does not include formatting of any decimals/numbers in currency or as part of a cost.

This ticket is complete when:
- [x] We have a common component we can use to render decimals in a format that's expected by each of our supported languages
- [x] We render all popularities, winrates and other decimals using this common component
- [x] We have verified that after setting the language to German, we see every decimal with a comma and numbers using a thousand separator with a dot.

**Comment by beheh** [comment]
Switched my recommendation to numbro, as numeral seems to be unmaintained ([related issue](https://github.com/adamwdraper/Numeral-js/issues/566)).

**Comment by beheh** [comment]
There's a shortcut we can take here, where instead of numbro we just use react-icu's formatting, as supplied by yahoo-intl. I.e.

`t('{n, plural, other {#}}', {n: number})`

inside the number component.

**Comment by azeier** [comment]
Started on this using numbro. Basics are working, seems fairly straight forward.
