### ISSUE TITLE
Supply deckstrings with Standard set

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#315]
Our deck template currently always supplies Wild deckstrings. If a user clicks through to the deck via https://hsreplay.net/decks/#gameType=RANKED_STANDARD he'll expect it to copy a Standard deck.

Copying Standard decks as Wild decks will require users to convert them manually, and will lead to users getting bad recommendations for missing cards if they don't realize the wrong format right away.

This is not only affects metatags, but also the "Click to Copy deckstring" buttons in the UI.

Related to HearthSim/Company-Tracker#93.

**Comment by beheh** [comment]
Standard Decks could be played in Wild - the frontend can dfferentiate what the user is looking at.

**Comment by jleclanche** [comment]
Not worth reimplementing this whole system for the odd case, at least not right now.
