### ISSUE TITLE
Add timestamps to Webhook signatures

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#322]
In order to prevent replay attacks, I will be following Stripe's lead and adding timestamps to webhook signatures. So a signature that previously looked like `X-Webhook-Signature: sha256=5257a869e7ecebeda32affa62cdca3fa51cad7e77a0e56ff536d0ce8e108d8bd` will now look like `X-Webhook-Signature: t=123456789, sha256=5257a869e7ecebeda32affa62cdca3fa51cad7e77a0e56ff536d0ce8e108d8bd`.

**Comment by beheh** [comment]
You're forgetting the crucial part of signing the timestamp. With 4d7d15c4f0d47079e469719b2617314862afef31 an attacker could just retransmit and replace the timestamp, thereby nullifying any protection against replay attacks.

You could follow Stripe's lead and concat the timestamp to the message, [as seen here](https://stripe.com/docs/webhooks#prepare-payload).

**Comment by jleclanche** [comment]
Separate issue please.

**Comment by beheh** [comment]
See #342.
