### ISSUE TITLE
Webhook Improvements To Support Tournament Brackets

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#325]
We need to make sure the webhooks support the following options:
- A toggle to be a single fire web hook or an open ended webhook that keeps firing until its deleted.
- The ability to set the match type, e.g. just friendly matches
- Being able to register the opponent's username
- (optionally) register a metadata string that is opaque to us that we send back along with the callback

**Comment by jleclanche** [comment]
Closing this as we're going in a different route with tournaments.
