### ISSUE TITLE
Add a redirect on static.hsreplay.net

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#35]
https://static.hsreplay.net/ root should redir to https://hsreplay.net/

**Comment by beheh** [comment]
Is not used anymore.

**Comment by jleclanche** [comment]
We'll use it again, though.

**Comment by jleclanche** [comment]
https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/

**Comment by beheh** [comment]
Is the plan still to use this?

**Comment by jleclanche** [comment]
Moved to https://github.com/HearthSim/server-provisioning/issues/10
