### ISSUE TITLE
Deck doesn't update global stats

### ISSUE THREAD

**Issue by Al3ksBG** [HearthSim/HSReplay.net#362]
For whatever reason this deck doesn't want to update the global stats panel.

When I created it, immediately the Deck stats/Mul guide button worked and linked to the proper page, however no global stats.

Then I tried linking it manually to that page, nothing happened with the global stats yet again...

Any ideas ?

![sasdasdasd](https://user-images.githubusercontent.com/18414596/27678936-b8bcec16-5cbf-11e7-8447-baed1eacaaeb.png)

**Comment by azeier** [comment]
Could you post the code for that deck? (rightclick > export)

Setting the url on a deck doesn't matter for this case.

**Comment by Al3ksBG** [comment]
AAEBAQcEsAKvBIQXkbwCDRyRA/8DjgWoBdQF7gbnB+8HjQ77D4KwAoiwAgA=

**Comment by azeier** [comment]
Issue moved to [HearthSim/Hearthstone-Deck-Tracker #3313](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3313) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Al3ksBG** [comment]
Cool :)
