### ISSUE TITLE
Fix DataManager request/retry behaviour

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#365]
When clicking around on pages while waiting for a 202 to finish up, one can very easily enter the "Please try again later" error state. I presume the promises happen to be enqueued in parallel, and the counter increases even if it's not the automatic retry triggering the counter to increase (but the user clicking around).

Additionally, once a specific request completes, it `.then`'s even if another query has been requested and fetched in the meantime. E.g. clicking "Last 3 days", receiving a 202, then clicking "Last 7 days" and looking at the output will result in continued automatic retries for the "Last 3 days" query. Once those suceed, they overwrite whatever is currently displayed in the view and we enter a missmatch between state/selection. This should never happen with correct state handling.

**Comment by azeier** [comment]
Second part is fixed with https://github.com/HearthSim/HSReplay.net/commit/9dad7aab857859dcf139b23ba26ca41b9c37fece.

I don't understand the first part.

**Comment by beheh** [comment]
There seems to be a retry counter. If a link 202s often enough in succession, it shows "Please try again later". If you click around the UI and retrigger a query that results in a 202 multiple times in quick succession you reach the "Please try again later" failure state within a few clicks.

**Comment by azeier** [comment]
The retry count is only ever [incremented](https://github.com/HearthSim/HSReplay.net/blob/master/hsreplaynet/static/scripts/src/components/DataInjector.tsx#L111) after the retry is ["enqueued"](https://github.com/HearthSim/HSReplay.net/blob/master/hsreplaynet/static/scripts/src/components/DataInjector.tsx#L107)

**Comment by azeier** [comment]
Though, I think the same fix used for the second part applies here as well. An out of date, failed query is able to update the state.

**Comment by beheh** [comment]
This has been done.
