### ISSUE TITLE
Add a graph for deck prediction accuracy verification

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#408]
We need to determine statistically how many cards are played in 90% percentile of games for the fastest archetypes. This number represents the lower bound on how many revealed cards we must require before we attempt deck prediction to ensure we aren't being overly general in our predictions.

This task is basically doing the analysis via Ad-Hoc Redshift queries.

**Comment by jleclanche** [comment]
Gonna test verification data against full decks.

**Comment by jleclanche** [comment]
I'm putting this on hold until we figure out why the metrics are causing issues in processing.

**Comment by jleclanche** [comment]
Andrew suggested using the build_deck_prediction_tree command.

**Comment by jleclanche** [comment]
We have that actually.
