### ISSUE TITLE
Add a FullArchetypeRefresh Command to Jenkins or the Admin

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#412]
This command will orchestrate the execution of multiple other sub-jobs. The expected use case for this command is whenever we have created a new Archetype and added some training data, or when we have gone through and scrubbed the ArchetypeTrainingData we will trigger this job to see the results of our work reflected in the UI.

The sub-jobs are:

Job 1) Recalculate all of the ArchetypeSignatures
Job 2) Create a new test fixture and install it in the Test Data Repository
Job 3) Reclassify all the active full decks from the last 14 days.
Job 4) Mark all the archetype data in the redshift query cache as stale and requeue it to be regenerated.

**Comment by jleclanche** [comment]
"Reclassify all the active full decks from the last 14 days." which job is this?

**Comment by jleclanche** [comment]
Done.
