### ISSUE TITLE
Unpaginate Archetypes & Archetype Training Deck Archetypes

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#417]

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/HSReplay.net/commit/b1252e31ae3cf1f4e38b22d4ad1447f088d6198f

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/HSReplay.net/commit/e444e628b52a47af09f476b67c3a4e7ce66a0e33
