### ISSUE TITLE
Decklist on Replay Details Is Missing Cards

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#43]
Compare the card revealed in the replay for player "Red1010" compared to the cards listed below Joust for the player. Only two cards are listed even though many more were revealed during the game:

https://hsreplay.net/replay/Su25oGmQg79RFXLFuj8qMC

**Comment by beheh** [comment]
Can reproduce by reingesting the corresponding Power.log: https://gist.github.com/beheh/6cf25812863e4a62e2f22bce4ac3699b.

**Comment by beheh** [comment]
Working on it upstream.

**Comment by beheh** [comment]
Fixed upstream, waiting for `python-hearthstone` release.

**Comment by beheh** [comment]
Fixed and deployed: https://hsreplay.net/replay/ShNCVsM6uaS74R5vgasQkS (test data, so will get deleted at some point).
