### ISSUE TITLE
Exporter missing hero cards

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#451]
Example game: https://hsreplay.net/replay/RSETUSAQFgJMV6e5gqhskC
Opponent played the Shaman Deathknight card, but it is not in the card list.
API: https://hsreplay.net/api/v1/games/RSETUSAQFgJMV6e5gqhskC/
```
    "opposing_deck": {
        "digest": "55f63bcc1295ad8f21a9be1bddb83ab3",
        "size": 15,
        "cards": [
            "CFM_637",
            "OG_027",
            "OG_027",
            "EX1_565",
            "OG_028",
            "KAR_073",
            "CS2_046",
            "CS2_046",
            "UNG_201",
            "UNG_201",
            "CFM_717",
            "CFM_717",
            "ICC_901",
            "ICC_466",
            "CFM_707"
        ]
    },
```
Missing: `ICC_481`

More importantly: We can also see this issue in redshift when querying for decks containing Death Knight cards without `full_deck_known`.

**Comment by azeier** [comment]
Needs verification that this is fixed

**Comment by jleclanche** [comment]
It's fixed.
