### ISSUE TITLE
Process UNKNOWN HUMAN PLAYER names differently

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#48]
Store them as a flag or something

**Comment by beheh** [comment]
Is UNKNOWN HUMAN PLAYER a valid battletag?

**Comment by jleclanche** [comment]
eh?

**Comment by beheh** [comment]
Could we actually run into real players called `UNKNOWN HUMAN PLAYER`?

**Comment by jleclanche** [comment]
No? Does it matter either way? It's impossible to know either way.

**Comment by manuel-delverme** [comment]
no; too long and has spaces
