### ISSUE TITLE
Create end-points for supporting Extension Setup

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#489]
Extension setup iFrame needs an endpoint to query whether the streamer has fully linked their Twitch account and HDT instance. This end point must validate the response is properly signed via JWT as a message from Twitch's servers. The end point can reply that the user is in 3 possible states:
	- The individual's Twitch Account is not linked to a HSReplay.net User. This response should provide a link for them to connect their account.
	- The individual's Twitch Account is linked to an HSReplay.net User, but there is no claimed AuthToken attached to that account. They should be provided with instructions for how to do this.
        - The individual's Twitch Account is linked, and there is also a claimed AuthToken - They are fully setup! This response should include the date of the last replay uploaded with that AuthToken to help debug instances where they have an old claimed AuthToken but the AuthToken they are currently using is not actually claimed yet.

**Comment by amw2104** [comment]
A second endpoint is needed if the extension configuration determines that the account is fully configured. This end point gets hit and the "greenlight" endpoint verifies itself that everything is good and then does a POST to the Twitch API to activate the Extension.

**Comment by amw2104** [comment]
These ends points should be extension version aware.

**Comment by beheh** [comment]
Remaining work is happening in #476.
