### ISSUE TITLE
Live data on front page stops updating after a while

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#494]

**Comment by azeier** [comment]
Pushed a frontend workaround, this appears to be a serverside issue though:

Network Timestamp | Data Time Range | Network Delta | Data Delta
--- | --- | --- | ---
Fri, 22 Sep 2017 09:44:25 GMT| 1506073405 - 1506073465 |   -| -
Fri, 22 Sep 2017 09:45:16 GMT| 1506073455 - 1506073515 | +51| +50
Fri, 22 Sep 2017 09:46:06 GMT| 1506073505 - 1506073565 | +50| +50
Fri, 22 Sep 2017 09:46:56 GMT| 1506073555 - 1506073615 | +50| +50
Fri, 22 Sep 2017 09:47:46 GMT| 1506073605 - 1506073665 | +50| +50
Fri, 22 Sep 2017 09:48:36 GMT| 1506073545 - 1506073605 | +50| -60
Fri, 22 Sep 2017 09:48:41 GMT| 1506073550 - 1506073610 | +5|  +5
Fri, 22 Sep 2017 09:48:46 GMT| 1506073555 - 1506073615 | +5|  +5
Fri, 22 Sep 2017 09:48:51 GMT| 1506073670 - 1506073730 | +5| +115
Fri, 22 Sep 2017 09:49:46 GMT| 1506073725 - 1506073785 | +55| +55
Fri, 22 Sep 2017 09:50:41 GMT| 1506073780 - 1506073840 | +55| +55
Fri, 22 Sep 2017 09:51:37 GMT| 1506073835 - 1506073895 | +56| +55
Fri, 22 Sep 2017 09:52:32 GMT| 1506073890 - 1506073950 | +55| +55
Fri, 22 Sep 2017 09:53:27 GMT| 1506073945 - 1506074005 | +55| +55
Fri, 22 Sep 2017 09:54:22 GMT| 1506074000 - 1506074060 | +55| +55
Fri, 22 Sep 2017 09:55:17 GMT| 1506074055 - 1506074115 | +55| +55
Fri, 22 Sep 2017 09:56:12 GMT| 1506074110 - 1506074170 | +55| +55
Fri, 22 Sep 2017 09:57:07 GMT| 1506074055 - 1506074115 | +55| -65
Fri, 22 Sep 2017 09:57:12 GMT| 1506074170 - 1506074230 | +5|  +115
Fri, 22 Sep 2017 09:58:07 GMT| 1506074230 - 1506074290 | +55| +50
Fri, 22 Sep 2017 09:59:08 GMT| 1506074175 - 1506074235 | +61| -55

**Comment by amw2104** [comment]
I think I fixed by using live data redis clock to prevent differences in server clock drift between web UI nodes.
