### ISSUE TITLE
Make Archetype Details degrade more gracefully

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#514]
While scrubbing archetypes on the Discover page this morning I decide to name a new "Stealth Rogue" cluster. I then reclassified the last 7 days of decks and refreshed all the archetype queries so that we would have data on them.

However, while all the backlog of archetype queries is getting crunched, we need to show more graceful messages for the missing data points, e.g. "Calculating... check back soon."

![image](https://user-images.githubusercontent.com/2694638/31085124-53ed0e2a-a764-11e7-9e19-84a51b4d2cb6.png)

**Comment by azeier** [comment]
Should be better now. https://github.com/HearthSim/HSReplay.net/commit/3418ce9fe8ec593d4729dcb37e11b0482327f9bd
