### ISSUE TITLE
Proposed Solution To My Decks / My Statistics Issues

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#522]
* [ ] Power "My Decks" from Postgres - That way people will always see the deck they just played in the deck list right after they finish playing and check the site. I think this creates a lot of confusion and perception of brokenness.
* [ ] Use Firehose Pattern For Synching Premium Account Status - Will be more stable and is much better for the cluster throughput anyway as each Insert / Commit is expensive. Would work like archeype_map.
* [x] Require Min 5 games (maybe even more) before My Statistics will show anything and add proper messaging to explain this to users. This will both make the statistics more meaningful when they are available and create more time for a few ETL tracks to have closed over the course of those games getting played.

**Comment by beheh** [comment]
This is split up into other issues.
