### ISSUE TITLE
Create Tournament Data Model

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#552]
We will need the following models with at least the following fields:

**Tournament**
  id (PK)
  creator (FK) - Used for controlling access and permissions
  num_participants
  num_decks_per_participant 
  status (Needs Configuration [DEFAULT], Ready, In Progress, Finished)

NOTE: The status of the Tournament will not proceed to “Ready” until the right number of participants have been created and each participant has the expected number of decks attached.

**Participant**
  id (PK)
  tournament_id (FK)
  player_account_battletag (Required)
  internal_account_battletag (Required)

NOTE: (Tournament ID, Player Account BattleTag, Internal Account BattleTag) create a unique index together.

**Participant_Deck**
  participant_id (FK)
  deckstring
  deck_id
  selected_archetype_id (FK)

**Tournament_Game**
  tournament_id (FK)
  replay_shortID

**Comment by beheh** [comment]
This might be replaced by a data model as provided upstream from Blizzard's eSports API.

**Comment by jleclanche** [comment]
Closing. This won't happen in this repo if it does happen (and it's been reprioritized for now).
