### ISSUE TITLE
Create Tournament Views

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#553]
**View: List Tournaments**
* Will only list the Tournaments created by that user
* Button to create tournament
* Button to edit existing tournament
* Summary data for each tournament on each row

**View: Edit Tournament**
* Edit name
* Edit slug (unique)
* Add / Edit Tournament Participant

**View: Edit A Tournament_Participant**
* Full Battletag, e.g. “Pavel#1573”
* Internal Account Battletag, e.g. “InternalAccount#4325”
* Does the participant have the proper number of decks configured?
* Add / Edit Participant Deck

**View: Add / Edit Participant Deck**
* Deckstring
* Deck ID (FK)
* Select Archetype (Including None)

Note: The archetype selector should be disabled until we have the deckstring. Then based on the deckstring we should attempt to classify the deck on the fly if it doesn’t already exist, and suggest the archetype that we think it is and enable the control for the admin to override it. The user must be able to override their selected archetype without it actually changing what we have assigned the deck as. They must also be able to set it to “None” if nothing matches.

**Comment by amw2104** [comment]
This is on hold until we determine whether or not we need to create our own homebrew tournament metadata capturing screens.

**Comment by jleclanche** [comment]
Closing this for the time being as things changed quite a lot.
