### ISSUE TITLE
Create Tournament APIs

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#554]
**GET /api/v1/tournaments/** - This will only list the tournaments created by the authenticated user.

**GET /api/v1/tournaments/<TournamentID>/** - This will include all the Tournament Player Info

**POST /api/v1/tournaments/<TournamentID>/associate_game/** - This will create a Tournament_Game record linking a replay to a tournament.

<- {“shortid”: “AAAAaaaa”, “id”: 1}
-> {“object”: “TournamentGame”, “id”: 1234, “replay_shortid”: “AAAaaa”, “tournament_id”: 1}

**Comment by amw2104** [comment]
If we end up using the eSports API then this story becomes:

* Create an API end point, protected by OAuth, that the broadcast tool will use to query for a list of the upcoming tournaments.

* Create an API end point, protected by OAuth, that the broadcast tool will use to pull all the deckstring data for whichever tournament has been selected.

* Create an API end point which the broadcaster tool will use to submit the shortID and tournament ID for each replay that gets uploaded during the broadcast.

**Comment by jleclanche** [comment]
All done.
