### ISSUE TITLE
Make analytics views RESTful

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#557]
We can use DRF to make the views a bit simpler. Especially the `query` view could use DRFs error handling instead of a mix of raising HTTP404 and returning HTTPResponses. While we're at it we could standardize the error response instead of just returning no body (and leaving it up to the implementor to interpret the status code).

**Comment by jleclanche** [comment]
#245

**Comment by beheh** [comment]
Oh, right.

**Comment by beheh** [comment]
Right. Duplicate of #245.
