### ISSUE TITLE
Add Secret to list of card mechanics?

### ISSUE THREAD

**Issue by kevinb9n** [HearthSim/HSReplay.net#568]
I'd like to filter the card list to list only Secrets.

**Comment by kevinb9n** [comment]
(It seems like this could be easy to fix, but however the card database is stored it doesn't seem to be searchable by github.)

**Comment by kevinb9n** [comment]
Thanks!

**Comment by jleclanche** [comment]
Done! Will be live very soon. Thanks for the report.

The database comes from here: https://hearthstonejson.com/

**Comment by kevinb9n** [comment]
Ahh, so I was hoping that this would eliminate cards like Flare from the results. The way it is now seems equivalent to just text-searching for "secret", which I could already do.  In theory, *should* a card like Flare be matched by this?  I can take it up on the hearthstonejson issue tracker but I don't know I'm just off base here.

**Comment by jleclanche** [comment]
The mechanics tab searches for card mechanics, which specifically looks for what cards interact with ("referenced tags") on top of what they actually are. In other words, you'd find Mad Scientist and Flare even if they didn't have card text.
That's the intended behaviour at the moment as it affects all mechanics.

**Comment by kevinb9n** [comment]
Thanks for clarifying. That makes sense. I notice a few cards are missing some of these referenced tags (e.g. Fandral does not have Choose One and Twilight's Call lacks Deathrattle); should I report these to hsjson?

In theory at least, it would make sense to distinguish between whether you want to filter cards that *reference* the mechanic or those that *possess* the mechanic (in the sense that cards like Corpsetaker respect, and the sense that I wanted for my Secrets query). But first that distinction would have to exist in the database and I'm not sure it does, so I don't know if I should file a request over there about that.

Thanks!

**Comment by jleclanche** [comment]
>  should I report these to hsjson?

The data on hearthstonejson is straight from the game. If it's missing in mechanics, it most likely doesn't have an appropriate tooltip in game; you should report them to Blizzard :)

> But first that distinction would have to exist in the database and I'm not sure it does

Sure does, it's just not a feature most users are interested in afaik, would probably be more confusing than helpful.

**Comment by jleclanche** [comment]
PS, feel free to swing by the two Discord channels:

https://discord.gg/hearthsim
https://discord.gg/hearthsim-devs
