### ISSUE TITLE
Retain sort order in Gallery view

### ISSUE THREAD

**Issue by kevinb9n** [HearthSim/HSReplay.net#569]
When switching from Statistics view to Gallery view in the Cards interface it would be great to preserve the order I had chosen to view the cards in.

**Comment by beheh** [comment]
If we just kept the sort order I think it would be slightly confusing right now, since we don't expose a sort control on the gallery page. So we would be either exposing some sort of sort control on that page, or not do this.

**Comment by beheh** [comment]
We won't be doing this.

**Comment by kevinb9n** [comment]
I see your point. In the unlikely event this ever comes up again, I thought I should record my use case:  As a casual player I can never remember all the Secrets.  I wanted to be able to view the Mage Secrets, Hunter Secrets, etc., with full card images (since I can't remember what they do) but in popularity order (so I know what's likely to trip).
