### ISSUE TITLE
Psychic Scream Card has Dragon Fury Image

### ISSUE THREAD

**Issue by ruthnaebeck** [HearthSim/HSReplay.net#573]
https://hsreplay.net/cards/43112/psychic-scream

Currently looks like this:
![image](https://user-images.githubusercontent.com/19349244/34419142-38dd123c-ebd0-11e7-967a-d934540d69cc.png)

Should look like this:
![image](https://user-images.githubusercontent.com/19349244/34419224-9fd5c628-ebd0-11e7-834c-4edfa6018700.png)

**Comment by azeier** [comment]
Tracked here: https://github.com/HearthSim/HearthstoneJSON/issues/55
