### ISSUE TITLE
Move intermediate static files from static/ to the build directory

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#58]
- [x] Webpack bundles
- [ ] Compiles CSS

**Comment by beheh** [comment]
Which ones do you mean? The raw Typescript/SASS files? And what is the build directory?

**Comment by jleclanche** [comment]
@beheh We have three types of static files:

* Source files. Those are the sass/ts ones.
* Transient files - The ones built by scss/webpack/whatever
* Processed staticfiles - Once picked up by django's staticfiles process.

The latter two should live in the `$BASEDIR/build` directory. Processed ones already do, but transient ones are still in `hsreplaynet/static/`. This is up for discussion if you have a better suggestion though.

**Comment by beheh** [comment]
Done for Webpack, need to figure out SCSS.
