### ISSUE TITLE
Add a referral link mention block on /premium/

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#588]
We want to talk about the referral link program on the Premium page. The block should be above the fold, collapsed for non-premium users by default. Expanding it should send a GA event.

**Comment by jleclanche** [comment]
Once done, the "Premium" link in the nav bar should be updated to say "Refer a friend".

**Comment by jleclanche** [comment]
This is done but needs styling and GA events.

**Comment by beheh** [comment]
Done.
