### ISSUE TITLE
[Andrew] Reclassify archetype command produces results inconsistent with classify_deck()

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#621]
We think the reclassify command for decks does not use the weighted signature.

https://hsreplay.net/discover/#playerClass=PALADIN&tab=5

https://hsreplay.net/decks/HdOpZBWt6lNAkhcSqVncCf/

**Comment by azeier** [comment]
We figured this out. The reclassify archetype command was picking a random game from which to take the deck from, which in many cases was an incomplete deck.

Fixed with https://github.com/HearthSim/HSReplay.net/commit/0319e830190acaca341b4a21b37779d0f0b9c5a4
