### ISSUE TITLE
Deck header bug

### ISSUE THREAD

**Issue by kadavr95** [HearthSim/HSReplay.net#675]
Deck headers in Replays section can not detect actual player class, just displaying a fallback option instead.

![image](https://user-images.githubusercontent.com/8514685/37522343-a8998a46-2934-11e8-8dc4-a47eb9731b35.png)

**Comment by kadavr95** [comment]
Well, deck headers do show correct player class (except Tavern Brawls like Ragnaros vs Nefarian where fallback option is showed instead(meh, but I think it is not that easy to fix and brawls like this are not often) and Adventures where it is blank(and it is correct behaviour) now, but the selected Hero portrait of that class doesn't represent the Hero what has been used in game. It shows something like Hearthstone default hero portrait (except Paladin, where for me it is showing Liadrin while default is Arthas) for both of player and opponent.
![image](https://user-images.githubusercontent.com/8514685/37555835-fce53d00-29fe-11e8-89e2-9af9b95c8124.png)
Bugs, bugs everywhere 
![image](https://user-images.githubusercontent.com/8514685/37555965-b6f767c6-2a00-11e8-86e0-9d6d1af3dd91.png)

**Comment by jleclanche** [comment]
> *but the selected Hero portrait of that class doesn't represent the Hero what has been used in game*

That was always the case. We could change it to match the in-game hero, I guess that makes sense, maybe.

> *Bugs, bugs everywhere*

What's the problem?

**Comment by kadavr95** [comment]
If it has always been like that, than so be it. I'd prefer to have portraits consistency of course but there are more important things you can do now.
Atramedes has never been playable hero in brawl, only BRM boss and minion in Ragnaros vs Nefarian, but it's displayed as hero for both player and opponent for all games in brawl # 114. Individual replay pages show normal heroes. But it was long ago so, again, for me it is not the task to think about now. Also some replays for Brawls and for Adventures have no decks. It's a pity but probably these are not bugs.
