### ISSUE TITLE
Add a locale switcher

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#677]

**Comment by beheh** [comment]
I don't think that's where it should be. Logged out users should be able to switch as well.

**Comment by jleclanche** [comment]
@beheh Yeah you're right, it should be somewhere easily accessible though, I imagine somewhere in the top-right near the account dropdown at least.

**Comment by jleclanche** [comment]
Mockup (glyphicon-globe):

![image](https://user-images.githubusercontent.com/235410/37566716-b3e30bec-2ac5-11e8-810d-dc339f12c2ee.png)
