### ISSUE TITLE
Replay doesn't show opponent's deck

### ISSUE THREAD

**Issue by riQQ** [HearthSim/HSReplay.net#678]
https://hsreplay.net/replay/6YTxweBqY7abUqx43JE7DH

**Comment by beheh** [comment]
The API reports

```json
"opposing_deck": {
    "digest": "d41d8cd98f00b204e9800998ecf8427e",
    "size": 0,
    "cards": [],
    "predicted_cards": null
}
```

**Comment by riQQ** [comment]
HDT problem then?

**Comment by beheh** [comment]
No, the decklist should be generated by the exporter, based on the played cards. @jleclanche?

**Comment by riQQ** [comment]
Broken replays can't be repaired, right?
