### ISSUE TITLE
Ensure we can scale heroes to more playable cards

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#679]
Since there's a new playable hero release in GIL we should make sure there's no hacks that assume only the ICC heroes are playable.

**Comment by azeier** [comment]
```javascript
export function isPlayableCard(card: any) {
	if (card.type === "HERO") {
		// default heroes/skins are not collectible
		return ["CORE", "HERO_SKINS"].indexOf(card.set) === -1;
	}
	return ["MINION", "SPELL", "WEAPON"].indexOf(card.type) !== -1;
}
```
[helpers.ts](https://github.com/HearthSim/HSReplay.net/blob/980e9555e7eaf19dd43e882cfc27dd5e33b3c4ba/hsreplaynet/static/scripts/src/helpers.ts#L276)

We should be good.

**Comment by jleclanche** [comment]
Turns out there was a place in the backend where IDs were hardcoded. All good now.
