### ISSUE TITLE
Add funnel metrics for checkout modal

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#704]
Once #685 is done we'll be using Stripe Elements everywhere and can access 3D Secure details with ease. At the very least we should ensure we're showing a message and log how often a user is unable to complete the checkout because their card requires 3D secure.

**Comment by jleclanche** [comment]
This is data we can easily get out of Stripe (or dj-stripe), so we don't need extra instrumentation around this.

**Comment by beheh** [comment]
I want to correlate this into GA so we have a funnel similar to the collection modal.

**Comment by beheh** [comment]
We did this.
