### ISSUE TITLE
Wrong game type shown

### ISSUE THREAD

**Issue by LordDrew** [HearthSim/HSReplay.net#71]
I have a friendly match replay in HDT(v1.1.0).
![image](https://cloud.githubusercontent.com/assets/3865783/18792077/d3daf926-81bd-11e6-9fec-28f922cf3210.png)
But on the site it is marked as "Ranked" game.
https://hsreplay.net/replay/XTXedUwnQkjGWF2ggrDXn4

**Comment by beheh** [comment]
Can confirm: https://hsreplay.net/replay/K2dcVqz7Tr3VNZjjQR8v5m.

**Comment by jleclanche** [comment]
Thanks for the report!
