### ISSUE TITLE
Deck that literally cannot have Cube labelled as Cube Warlock

### ISSUE THREAD

**Issue by ericrboidi** [HearthSim/HSReplay.net#749]
https://hsreplay.net/decks/gxqEeQkB3MEvoeEmp0ZDFg

It's an even deck, so it is impossible for it to have Cube.

**Comment by beheh** [comment]
Thanks for your report! Missclassified decks are caused by various small issues in our classification systems. We're continuously looking into improving these systems, so thanks for your feedback.
