### ISSUE TITLE
Add download to CSV link to current Matchups tab

### ISSUE THREAD

**Issue by bugladen** [HearthSim/HSReplay.net#770]

**Comment by bugladen** [comment]
And by meta, sorry, I mean the matchups tab.  That "spreadsheet" is what I'm requesting to be downloadable into a CSV.

**Comment by beheh** [comment]
What are you specifically interested in doing with the data?

**Comment by bugladen** [comment]
I have a google sheet that I paste the matchup data to.  I then record every play in another sheet.  Based on what decks I play I can run formulas on the log + the matchups to determine my own personal meta and what deck has the highest percentrage to win at the moment.  It's actually pretty easy to implement if you want a copy of the sheet, and think about adding it as a feature to HSReplay.

**Comment by beheh** [comment]
Yeah, feel free share it with us! We're interested in learning about how players use our data, and how to integrate useful features natively into the site.
