### ISSUE TITLE
Add an /embed view for replays

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#78]

**Comment by jleclanche** [comment]
@beheh The basic view for it is done. [Example](https://dev.hsreplay.net/replay/UDkdWaMo9g5UqaAWYqtKGi/embed).

Here's what I need you to do to close this:

1. Rework the structure of the bundle so that "embedding joust" and "rendering the details page" is separate
2. Fix the css issues on the page
3. Make sure it doesn't depend on jquery
4. Make sure it doesn't depend on the infobox div
5. Ensure it works as an iframe embed

Finally, I also need you to check whether the firefox svg shim is still needed in the latest Firefox release.

**Comment by beheh** [comment]
You duplicated some of my work from the embed branch. I'll merge it later.

**Comment by jleclanche** [comment]
This is done now.
