### ISSUE TITLE
Setup deck prediction experiments

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#790]
As a developer, I want to be able to try out a new deck prediction algorithms and have them run on a standalone cluster to find the most effective variation.

This work is related to improving the deck prediction performance in order to reduce the size of the "Other" archetype category.

This ticket is complete when:
- [ ] We want to rewrite the deck prediction procesing part so that we can run additional versions of deck prediction aside the current ("primary") deck prediction logic
- [ ] These deck prediction experiments emit the same metrics as the primary deck prediction logic
- [ ] The emitted deck prediction metrics are tagged with the experiment, so we can see exactly which experiment emitted these metrics
- [ ] Grafana is configured to show a dropdown so the developer can select any single experiment
- [ ] A developer can setup a new experiment by provisioning a new cluster, which means adding to AWS either via Teraform or the Dashboard, run the Redshift command to initialize the cluster, add the cluster to the  list of caches in the settings and add his custom experimental code to processing. 
- [ ] We have at least one additional experiment provisioned and running to compare it's performance with the primary algorithm's performance

**Comment by joolean** [comment]
Can we close this?

**Comment by beheh** [comment]
For now I think so, yes.
