### ISSUE TITLE
Implement deck importing via meta tags

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#80]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2769

If we want others to use it, we should probably do so as well.

**Comment by jleclanche** [comment]
This is done, but we have neither a deck name nor a hero id:

```html
<meta property="x-hearthstone:deck" content=""/>
<!-- <meta property="x-hearthstone:deck:hero" content=""/> -->
```

We need to be able to autogenerate both especially if we want a proper page title.
