### ISSUE TITLE
Add a marketing email optin on signup and on email page

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#801]
GDPR compliance to match new privacy policy. We're not sending any marketing emails right now, but I want to have that setting live beforehand anyway.

We'll add a column with an explicit opt-in/opt-out choice and the date this happened on.

**Comment by beheh** [comment]
Add a column marking explicit consent to email marketing.

**Comment by amw2104** [comment]
We need a mechanism to clearly identify all the e-mail addresses that we captured prior to having an explicit opt-in check box.
