### ISSUE TITLE
Standardize glossary term for winrate

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#804]
We've spelled it a few different ways: `winrate`, `win rate` and `win-rate`. We need to standardize on something. This includes for articles.

**Comment by jleclanche** [comment]
Also Match vs. Game (and when to use "Replay").

**Comment by beheh** [comment]
```
~> ack -icl "winrate" | cut -d ":" -f 2 | jq -s 'add'
359
~> ack -icl "win rate" | cut -d ":" -f 2 | jq -s 'add'
null
~> ack -icl "win-rate" | cut -d ":" -f 2 | jq -s 'add'
2
```

I think we're pretty consistent with regards to "winrate". We should enforce it on articles.

**Comment by joolean** [comment]
Closing: Let's enforce this for new code / articles and passively fix existing instances as we find them.

**Comment by jleclanche** [comment]
So we're going with winrate, yeah?
