### ISSUE TITLE
update_replay_feed should check for null user on GameReplay

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#809]
...because it's nullable, and because it'll be set to null when a user is deleted.

Right now, it's triggering an AttributeError when we attempt to verify that the user that submitted it has their replays visible by default.

This is reported in Sentry as "AttributeError hsreplaynet.games.processing in update_replay_feed"  (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/528945607/)

Created as part of #133.

**Comment by beheh** [comment]
:+1: should be a simple fix
