### ISSUE TITLE
TypeError in create_hsreplay_document

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#810]
Some bit of code in create_hsreplay_document is raising TypeError with the message: "int() argument must be a string, a bytes-like object or a number, not 'NoneType'"

The only way I can see this happening is if player.player_id is None.

This is reported in Sentry as "TypeError hsreplaynet.games.processing in create_hsreplay_document" (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/528760203/?query=is:unresolved)

Created as part of #133.

**Comment by beheh** [comment]
Sentry actually shows the stacktrace going all the way into python-hsreplay.

If you click the "Full" button to the top right of the [stacktrace](https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/528760203/?query=is:unresolved#exception) you can follow it into "third-party" libraries (which is ours as well in this case).

![grafik](https://user-images.githubusercontent.com/929769/40163961-857c83ba-59b8-11e8-8641-79a1b6a2b2b0.png)

The effect seems to stem from a missing effectindex on a block. I'm not sure under which circumstances Hearthstone would/wouldnt emit this.

In any case, the next step would be to move this issue or file an issue at [python-hsreplay](https://github.com/hearthsim/python-hsreplay) and implement a fix with test case, using such a Power.log.

**Comment by jleclanche** [comment]
I have this fixed already, I'll push it.

**Comment by jleclanche** [comment]
Fixed in https://github.com/HearthSim/python-hsreplay/commit/4692f35c5d62f6e6e054f94887d9845b147ac5df
