### ISSUE TITLE
Attempted CHANGE_ENTITY on an entity with no known card ID

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#811]
Parsing fails with the message "Attempted CHANGE_ENTITY on an entity with no known card ID." Looking at a few affected uploaded power logs, the relevant cards appear to include:

- (Lesser/Greater) Jasper Spellstone
- (Lesser/Greater) Ruby Spellstone
- Gilnean Royal Guard (Korean)

...which might be notable because these are cards that can change multiple times?

This is reported in Sentry as "ExporterError hsreplaynet.games.processing in validate_parser"  (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/537416952/)

Created as part of #133.

**Comment by jleclanche** [comment]
There's some cases where this is a legitimate error. I added a safeguard at some point against missing packets so the game gets rejected if it's bad.

But there might be something else to it with spellstones. Maybe Blizzard is publishing the CHANGE_ENTITY packet even if it's not seen now.

**Comment by joolean** [comment]
Closing: Low urgency.
