### ISSUE TITLE
Non-decodable Power.logs should trigger an error upon upload S3

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#818]
Specifically #812 has shown that a bad GZIP header causes exceptions during processing instead of a more graceful error state on the upload event.

**Comment by beheh** [comment]
We feel that a `VALIDATION_ERROR` in these cases makes most sense here.

**Comment by joolean** [comment]
Note: These should be distinguished (in the database / influx?) from other invalid uploads.
