### ISSUE TITLE
log in battle.net to claim replays NOT support china zone

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#82]
@sufre commented on [Mon Oct 03 2016](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2869)

the default url is 
https://us.battle.net/login/zh/?ref=https://us.battle.net/account/management/&app=bam&cr=true

plz add support to switch battlenet zone 

---

@jleclanche commented on [Mon Oct 03 2016](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2869#issuecomment-251013161)

Can you give more details on what's broken/where?

**Comment by sufre** [comment]
when i finished a game, i upload the replay to server by click the popup right-bottom
then i go to options -> replays ->claim account -> log in with battle.net, it leed me to the url of us zone battlenet login page.

i'm a player in china, my account cannot access from this page, so where can i see my replays uploaded?

**Comment by jleclanche** [comment]
Hey @sufre, can you tell me if you are able to log in from this page?

https://dev.hsreplay.net/

This runs on the china zone by default. If you're able to log in from there, I'll figure something out. If not, please let me know your battletag.

**Comment by sufre** [comment]
@jieclanche

sorry，go out few days，this page shows 500 You broke it! It's fine, we'll fix it.

is the server still ok？

**Comment by jleclanche** [comment]
@sufre Thank you, I see the problem. I'll push out a fix to dev as soon as I can, I might need you to try again once I do that :)

**Comment by jleclanche** [comment]
The allauth module currently hits `https://cn.api.battle.net/account/user?access_token=...` instead of `https://www.battlenet.com.cn/account/user?access_token=...`. I'll submit a fix.

**Comment by jleclanche** [comment]
The allauth PR is merged. We still need to figure out a good way of providing the user with the option to log in through China.

We also need to figure out a way of dynamically using the correct account adapter. Maybe we'll subclass the Allauth adapter, and customize the region based on some arguments, which we would have to get from somewhere...

**Comment by jleclanche** [comment]
Ok, so as it turns out there was a bunch more work needed to get this to work. And I did!

https://github.com/pennersr/django-allauth/pull/1556/ contains a bunch of commits to get allauth to support a `?region` parameter on the login page. With that technique, we can offer a region dropdown or a direct link to a china login url anywhere we want.

**Comment by chucklu** [comment]
hi,the url https://dev.hsreplay.net/ did not work now.
I remember I have signed in successfully by using the china account.
But now when I singed in,it's the same as the en-US account

**Comment by jleclanche** [comment]
@chucklu Hey, China logins are now on prod, they just don't have a UI yet.

You can hit this URL to log in with your chinese account:
https://hsreplay.net/account/battlenet/login/?region=cn

**Comment by jleclanche** [comment]
@chucklu @sufre @cheermc Hey guys, I know this took ages to implement, but we had to fix a lot of underlying stuff before this became possible. It's done now though! :D

Our main login page now supports the China region: https://hsreplay.net/account/login/ (You can pick your region from the dropdown)

I also added region selection to the [social connections page](https://dev.hsreplay.net/account/social/connections/), so if you already have an account you can connect your chinese one to it as well.
