### ISSUE TITLE
Fix Django-rendered HTML not displaying strings

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#826]
We expect Django to emit HTML with tagged strings replaced by their translations from the respective translation file. For example, the navbar is tagged and translated, yet it always appears in English.

This is done when the navbar and any other tagged and translated strings in templates are rendered in the currently selected language.

**Comment by jleclanche** [comment]
Should be fixed now that compiled messages are getting added to the build. Will see if it actually comes through.

**Comment by jleclanche** [comment]
Confirmed fixed
