### ISSUE TITLE
Tag all translateable strings in the Account section

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#827]
As a translator, I need a catalogue of all user-facing strings in the account section so that I can translate this part of the site into my language.

This is part of the ongoing translation project in order to translate the whole site. Most of the work for this ticket will be tagging Django templates (all files in account, billing, oauth2, socialaccount, webhooks, and any other templates visible in the account settings), and there might be some React code to translate (AccountDeletion). This should also include the OAuth approval dialogue.

Note: This does not include the site chrome (parts of the site that are visible on other pages).

This ticket is done:
- When we have provided translators with the full list of English strings visible in the account part of the site

**Comment by jleclanche** [comment]
Done. Ported most of it to React. There's still a couple of things that need cleaning up though (like SemanticAge usage etc).
