### ISSUE TITLE
Add user profiles

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#83]
@sdlorimor commented on [Mon Oct 03 2016](https://github.com/HearthSim/joust/issues/153)

Add a way one can link their entire set of games to another person, as opposed to having to link games one at a time.

---

@sdlorimor commented on [Mon Oct 03 2016](https://github.com/HearthSim/joust/issues/153#issuecomment-251043040)

And as always, thank you for your work.

**Comment by joolean** [comment]
Closing: Duplicates work captured elsewhere.
