### ISSUE TITLE
Tag all translateable strings for some miscellaneous pages

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#830]
As a translator, I want to be able to translate the user-facing strings features on the various pages as listed below.

This is part of the ongoing work to translate all pages. This does not include parts of the site visible on a majority of pages (site chrome).

This is done when:
- We have provided translators with the translateable strings on the following pages
  - [x] Premium Page
  - [x] Downloads page
  - [x] Coupon redemption page
  - [ ] Error pages (added back to discuss during retrospective)

**Comment by amw2104** [comment]
Closing, we will not translate error messages for now.
