### ISSUE TITLE
Create an HSReplay.net 3rd party API reference document

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#837]
As an HSReplay.net stakeholder, I want an API reference document for a proposed new set of APIs which will be how approved third parties can get access to our data, so that I can implement the new APIs described in the document in a future sprint and begin getting the benefit of partnering with 3rd parties. 

We have been approached by Bing, Hearthstone Top Decks, and Farsig.ht requesting permission to use some of our data on their sites. We would like to have a set of stable and versioned API endpoints which are independent of the internal APIs that we use on the primary site so that we can easily keep them stable and maintain backwards compatibility if we change our internal APIs in the future. These APIs for 3rd party use should require authentication so that we can disable access if needed. These APIs should also make clear as a policy that they define a minimum set of fields but that new fields may be added over time.

This ticket is to produce the API reference document that we will provide to Bing, Hearthstone Top Decks, and Farsig.ht. It should be sufficient that a developer not familiar with Hearthstone is able to use it to build new features.

This story is complete when:
- [x] The reference document describes APIs capable of satisfying Bing's needs.
- [x] The reference document describes how versioning will work, and our policy towards adding fields.
- [x] The reference document describes how authentication works.
- [x] A set of tickets has been written to implement the APIs described in the document.

**Comment by jleclanche** [comment]
If we go down that route, I really recommend Stripe's versioning system. It's been great to work with and it is simpler to both implement and maintain than other API schemes.

https://stripe.com/blog/api-versioning

**Comment by amw2104** [comment]
Some work in progress can be found here: 

https://docs.google.com/document/d/1i2NgMrGNTRJ4bqhE5JWQBpBiKGneihKugr4X2L1wAQk/edit#

Bing's requirements are here:

[hearthstone.entities.pptx](https://github.com/HearthSim/HSReplay.net/files/2055388/hearthstone.entities.pptx)

Hearthstone Top Decks requirements are here:
https://docs.google.com/document/d/1ace3GIk4AFxWu4a2tS3OXikW1-YmMDKfX5FerjEsgmE/edit

And Farsig.ht is currently temporarily using the following internal end point for the data points you can see displayed on their site.

https://hsreplay.net/analytics/query/card_included_popularity_report/?GameType=RANKED_STANDARD&TimeRange=CURRENT_EXPANSION&RankRange=ALL

**Comment by joolean** [comment]
- https://github.com/HearthSim/HSReplay.net/issues/861
- https://github.com/HearthSim/HSReplay.net/issues/862
- https://github.com/HearthSim/HSReplay.net/issues/863
- https://github.com/HearthSim/HSReplay.net/issues/864

**Comment by joolean** [comment]
Final draft, post incorporating feedback from Bing: https://hearthsim.atlassian.net/wiki/spaces/IN/pages/4816899/DRAFT+Partner+stats+API+documentation
