### ISSUE TITLE
Figure out a system for squashing DB migrations periodically

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#84]
The introduction of data migrations for native postgres code means deleting all the migrations and regenerating them can no longer be done as easily. We must be mindful to make sure to preserve the data migrations that exist.

An ideal solution would maintain all the nice continuous deployment machinery provided by the Django migrations framework, but allow us to continue to be able to squash all the accumulated migrations periodically much more easily than the built in squash migrations functionality makes possible.

**Comment by jleclanche** [comment]
Note: We just introduced django-oauth-toolkit which has a screwy swappable model dependency. It requires us to remove the swappable model setting when generating the migration.

**Comment by jleclanche** [comment]
I'm closing this because we're moving towards a system where the database migrations will be in more places.
