### ISSUE TITLE
Run Python test suite on Travis CI

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#843]
As an HSReplay.net developer, I want to be informed of python test failure after I push to a non-master branch or submit a PR, so that I can be confident I can merge this into master without risking a deploy failure due to failing tests.

Right now, we're running tests as part of deploys to prevent breakage, and we're running some linters during pushes and PRs via Travis. We should be copying what we're running only on deploys so that we can catch PRs or non-master branches breaking Python tests before we merge them to master.

This ticket is done when:
- [x] We have setup Travis to run the full Python test suite on every commit
- [x] We have at least one commit in master that resulted in a successful run of the full Python test suite without failures
- [ ] We use the same Tox commandline on Travis that we use on Jenkins

**Comment by beheh** [comment]
This is I think complete with the linked PR. Need to compare the tox commandlines still.

**Comment by joolean** [comment]
@beheh You wanna close this?

**Comment by beheh** [comment]
Yep. The last acceptance criteria isn't technically met as we don't emit a JUnit test report on Travis, but there's no infrastructure there to show that there anyway.
