### ISSUE TITLE
premium_account table is not updated when users unsubscribe

### ISSUE THREAD

**Issue by ChanmanV** [HearthSim/HSReplay.net#849]
The "active" column of the premium_account table in the Redshift is not being updated when we have users unsubscribe from the premium subscription.

**Comment by beheh** [comment]
That's not necessarily bad from a user's point of view, but it increases the payload size unnecessarily.

**Comment by joolean** [comment]
Duplicates https://github.com/HearthSim/hsredshift/issues/71
