### ISSUE TITLE
Remove Duplicate Indexes

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#85]
We appear to have several tables with duplicate indexes on them. 

1) The digest field on deck appears to have both a unique index and a regular index on the digest column. 

2) games_gamereplay appears to have a unique index and a non unique index on the shortid column.

I have not checked other tables, but I suspect there may be several duplicative indexes currently that need to be removed.

**Comment by jleclanche** [comment]
We cleaned this up.
