### ISSUE TITLE
Remove sources of slowdown in the large admin listings

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#86]
Looking at the sql stats, a ton of time is spent in the `COUNT(*)` query. Maybe setting `show_full_result_count` will be enough. Either way need to investigate.

**Comment by beheh** [comment]
`show_full_result_count` only affects filtered result pages (as per [this comment](https://code.djangoproject.com/ticket/8408#comment:45)), not the full page if you just open the admin (e.g. DeckAdmin, GlobalGameAdmin, or GameReplayAdmin).

A possible fix is to implement a custom paginator that doesn't do `COUNT(*)`. [There's a nice write-up here](https://www.raditha.com/blog/archives/django-admin-select-count-from-....html).

We also should be tracking [this Django issue](https://code.djangoproject.com/ticket/8408) I guess, in case they add another option.

**Comment by jleclanche** [comment]
Fixed mostly by e4bfd1d6be34c2fc83dbb6ef09567c24088a04e2. Still dropping some slowdown sources here and there but the biggest issue is gone now.
