### ISSUE TITLE
Authentication and authorization support for partner stats API

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#861]
As an operational stakeholder in HSReplay.net, I need to be able to authenticate and authorize users of the partner stats API, so that I can safely give our partners (like Bing) access to that API.

Our authentication strategy will be a truncated variant on the traditional OAuth 2.0 delegation flow, using long-lived access tokens. In particular, it requires:
- A new Django user permission granting access to the partner API
- At least one user to be created for each partner, which receives the partner API permission
- A new OAuth 2.0 scope for identifying the partner API as part of an OAuth token grant
- An application to be created for each partner, which is allowed to request the partner API scope
- An internal tool for generating long-lived access tokens for the partner applications on behalf of the partner users

The tool should generate a new OAuth 2.0 access token for an existing HSReplay.net user (specified by email address or BattleTag) and partner application (specified by client id) with the assigned scope `stats.partner:read`. It could be as simple as a Django `manage.py` command.

This story is complete when:
- [x] A version of HSReplay.net that supports this workflow has deployed to production
- [x] ~~The new user permission has been created and added to the hsreplaynet database via a migration~~ The new feature flag has been created in the hsreplaynet database (see comment below)
- [x] There are automated tests that exercise the access token-generation workflow
- [x] There is documentation in Confluence that describes the process for generating a new access token (https://hearthsim.atlassian.net/wiki/spaces/HSReplay/pages/13238273/Managing+Access+to+the+Partner+Stats+API)

**Comment by joolean** [comment]
- [ ] Implement auth token-granting Django command
- [ ] Write integration test to exercise token generation
- [ ] Add documentation to Confluence on how to create a new partner, auth token, and user permission
- [ ] Create the partner API permission (e.g. via migration)

**Comment by beheh** [comment]
Work is happening on the ` dev/partner-auth` branch.

**Comment by beheh** [comment]
We have replaced the Django permission system and migration usage with our own feature tag system. The feature tag is created by the management command upon first use.
