### ISSUE TITLE
Restore current arena season filter for Taverns of Time

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#867]
With Taverns of Time active, the arena season has changed. We should have a filter for arena stats for it.

Internal intercom ref: 17004832005

**Comment by beheh** [comment]
The current arena event filter has been active on the cards page since the starting day of Taverns of Time.

![Arena filter](https://user-images.githubusercontent.com/929769/41466893-7da649fc-70a4-11e8-8336-9b6f67153052.png)
