### ISSUE TITLE
Don't promote kinesis lambda to use canary code until canary succeeds

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#87]
Currently the kinesis code always uses $LATEST, which means that it automatically starts using whatever the latest canary deployment is. We need to make sure that this code doesn't get deployed until after the new logic has been verified via the canary process.

**Comment by jleclanche** [comment]
Closing this because it's a chunk of the work that'll happen with our lambda rework (and it's not really suited to this tracker anyway)
