### ISSUE TITLE
Code redemption problem

### ISSUE THREAD

**Issue by Zanermn** [HearthSim/HSReplay.net#871]
I have added a code and ahd a problem...
replay.net/features/redeem/?code=XXXXXX-02fc40ab-XXXX-29188512XXX
(Changed some numbers)
And It said that was ok, but I can't see any premium feature...
Please help
thanks
Zaner

**Comment by jleclanche** [comment]
Hi Zaner, you still need to purchase Premium from here: https://hsreplay.net/premium/ - the code just adds a coupon.

Please email contact@hsreplay.net for support issues in the future.

**Comment by Zanermn** [comment]
I won as a prize and they told me I will receive 1 month free premium, here I am sending you screenshot
![rrevv](https://user-images.githubusercontent.com/15325725/41547807-93f88d50-72f7-11e8-97ef-746bcf99e67a.JPG)

**Comment by jleclanche** [comment]
As I said, the code adds a coupon code to your account. You have to purchase premium. You won't be charged if the amount is less than the coupon you got ($5.00 USD)

**Comment by Zanermn** [comment]
So I have to buy the first 5 dolar premium and then the code appears?

**Comment by jleclanche** [comment]
If you redeemed the code, you should have a coupon showing up here: https://hsreplay.net/account/billing/

If it says you have a coupon for $5.00 off, then that amount will be removed from your next purchase. If that next purchase is $4.99, you will not be charged.
