### ISSUE TITLE
Work around i18next HOC performance issues

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#876]
As an HSReplay.net stakeholder, I want translations to be deployed to the site without the performance degrading, so that the site feels as fast as before.

We have a serious perfomance degradation due to i18next/react-i18next#456. This ticket was filed as part of #848.

Fixing this will require a serious rework of how state is handled inside the parts of the react-i18next library. You may read up on the above issue for context. The primary culprit is that a global object is used as the state for all available translations, and all translateable parts of the site attach an event to be notified once the translation is available. This in turn causes all the initial load (from untranslated => translated) trigger a large number of rerenders all around the codebase, instead of just one.

The easiest way for us to do this without waiting for upstream to come up with a fully compatible solution is to handle the state management ourselves. The high level plan is as follows:
- Write a t function provider component to provide a state object containing the `t` function (from `i18n.getFixedT`) with both namespaces (`frontend` and `hearthstone` as fallback) via the Context API. This will be consumed by the Higher Order Component (HOC). The state will be updated upon events from the i18next instance.
- Write a HOC to inject the translate (t) function into a components. The translate function is delivered via the (new) React context API.
- Write a drop-in replacement for the `translate()` wrapper call from `react-i18next`. This just wraps our HOC around the passed component.

This ticket is complete, when:
- [ ] We have updated our `Root` component to use the new t function provider
- [ ] We have written a Higher Order Component (HOC) thast consumes the t function from context and injects it as a Prop to the child component
- [ ] We have written a drop-in replacement for the `translate`-Wrapper
- [ ] We have updated `Root` and all disconnected roots with translations to use the new t function provider
- [ ] We have updated all the translate() calls around component classes to use our drop-in replacement
- [ ] We have verified that we're no longer running extraneous rerenders during translation initialization
- [ ] We have verified there is at maximum only a minimal performance impact when toggling the `frontend-translations` feature group

**Comment by beheh** [comment]
With the latest performance fixes from upstream applied to production, the underlying issue here has gotten much less severe. I think pursuing this story as written at this point will only yield a minor speed benefit, if at all.

**Comment by joolean** [comment]
Do you wanna close it then?

**Comment by beheh** [comment]
This is no longer required.
