### ISSUE TITLE
Implement Webmaster Tools Best Practices For Localization

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#882]
As a stakeholder in the global search visibility of HSReplay.net, I want to implement best practices around multilingual content targeting, so that I'm confident that Google's web crawlers can properly understand and index our translated content.

This story is based on a reading of https://support.google.com/webmasters/answer/182192?hl=en, which suggests that a GET parameter is a low-coast approach to multilingual SEO.

This story is complete when:
- [x] All pages with translated content are available via an URL that includes a language specifier - e.g., https://hsreplay.net/decks/?hl=fr
- [x] If the language specifier in the URL differs from the persistent language selection (performed via the language menu) the user should see content in the language from the URL, but the persistent language selection does not change
- [x] Each page includes `rel="alternate" hreflang="x"` link elements in its `head`, directing crawlers to alternate translations of its content, per https://support.google.com/webmasters/answer/189077
- [x] Each page includes a `rel="alternate" hreflang="x-default"` link element in its `head`, directing crawlers to an URL with no language specifier

**Comment by beheh** [comment]
Google has picked up the hreflang links (just the meta description hasn't been translated by us yet):

![Google](https://user-images.githubusercontent.com/929769/42213407-f012f720-7eb8-11e8-8b31-0aab81fdac80.png)

Looks like it's now only a matter of time until everything is translated and picked up

**Comment by jleclanche** [comment]
![image](https://user-images.githubusercontent.com/235410/42247047-b454be02-7f27-11e8-96c0-fe6314541377.png)
