### ISSUE TITLE
Use localized name in slugs for hreflang urls

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#887]
As a stakeholder in the search visibility performance of pages on HSReplay.net that include slugs in their URLs (such as the card details pages) I want search engine web crawlers to see fully translated URLs in the hreflang links in the page headers, so that it's clear to search engines that our site provides a good experience for users across all of our supported languages and our content is indexed and ranked accordingly.

Due to the way the hreflang logic works, our slugs look like this for all languages:

- https://hsreplay.net/cards/374/ragnaros-the-firelord/?hl=ru
- https://hsreplay.net/cards/374/ragnaros-the-firelord/?hl=fr
- https://hsreplay.net/cards/374/ragnaros-the-firelord/?hl=es

Right now the slug generation only happens in the current locale (see https://github.com/HearthSim/HSReplay.net/blob/master/hsreplaynet/web/html.py) since we delegate to the target object's `get_absolute_url` only once. We probably need to re-render the object's URL once per supported locale.

This story is complete when:
- [x] The slugs for the cards pages in the hreflang alternate `link`s in the card details page headers are rendered in the same language as the link target (i.e., the language given by the `hl` param) 
- [x] The relevant changes are covered by unit tests
- [x] We have a plan / strategy for how to handle the same issue for archetype detail pages once we begin to translate archetype names.

**Comment by joolean** [comment]
@jleclanche Can you explain the work necessary? Is this a matter of threading the locale / language through to the code that generates the slug?

**Comment by jleclanche** [comment]
That's exactly it, yes. Incidentally that already happens on the frontend due to the way the frontend generates the slugs.
