### ISSUE TITLE
Turn on frontend translations for all site visitors

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#896]
As a visitor to HSReplay.net, I expect to see the full part of the page in the language I expect.

This is the final ticket to complete the localization project on HSReplay.net to turn on the feature that is only visible to staff and translators right now.

This ticket is done, when:
- [x] We have set the `frontend-translations` feature to public
- [x] We have verified the translations are visible to all users and logged-out visitors of the site.

**Comment by jleclanche** [comment]
Done
