### ISSUE TITLE
Patch processing: Alarm-o-bot should log status of patch download

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#898]
As a Hearthsim engineer preparing to process a new Hearthstone patch, I want to know when Alarm-o-bot is done downloading the patch to ngdp.hearthsim.net, so that I know when it's safe to begin stepping through the patch processing procedure.

This story is complete when:
- [ ] Alarm-o-bot logs a message to the #alerts channel on the Hearthsim Discord server when the ngdptool patch download has completed successfully (exits with a zero exit code)
- [ ] Alarm-o-bot logs a message including the last 10 lines of stderr and stdout to the #alerts channel on the Hearthsim Discord server if the ngdptool patch download fails (exits with a non-zero exit code)

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/infrastructure #189](https://github.com/HearthSim/infrastructure/issues/189) via [**ZenHub**](https://www.zenhub.com/)
