### ISSUE TITLE
"My Collection" public page

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#917]
As an HSReplay.net user, now that I'm able to sync my collection to the site, I want to be able to see it and share it with my friends.

There is some disagreement as to how to fit this page into our navigation. One possible design is:
- In "Free" mode, the "My Cards" element in the top-level navigation links to the new collection page
- In "Premium" mode, the The "My Cards" menu in the navigation is a drop-down menu with options for navigating to the old My Cards page or the new collection page

This story completes once:

- [x] There is a page on the site which allows me to see all the cards I have and how many of them I have. Maybe reusing the /cards/ interface (cardlist, gallery mode?)
- [x] There is a way to navigate to the new page
- [x] We have designed and included cardset progress bars somewhere on the page, allowing users to see what % of a set they have acquired.
- [x] There is functionality on the page to tell what % of the set/total is golden
- [x] There is a dropdown somewhere on the page allowing you to make that collection visible to others under a unique url (eg. `/collections/{region}/{account_lo}/`).
- [x] The dropdown reuses and updates the existing `collection-visibility` key in the `User.settings` object. (There is an existing API for this, used in the user settings page)
- [ ] The checkbox in the user settings page to make the collection public has been removed

Once this story completes, we will write twitter/facebook/discord announcements for it, and maybe a blog post.

**Comment by azeier** [comment]
Random notes:
- We have the same set of filters as in /card/gallery: https://hsreplay.net/cards/#display=gallery
- We have a filter to show missing cards (blue-ish, faded)
- We have a filter to only show golden cards
- The progress indicators and summary stats sit at the top of the page while no set filter is selected
- Summary stats included expected dust value from packs, dust required to finish sets/collection, odds of opening a certain rarity (see https://github.com/HearthSim/Hearthstone-Collection-Tracker)
- Each card has a [x3, x1] label somewhere (normal, golden) 
- We could have a "recommended crafts" section based on our popularity/winrate data

**Comment by jleclanche** [comment]
> We could have a "recommended crafts" section based on our popularity/winrate data

I like that! Could even be premium

**Comment by joolean** [comment]
(Story includes all of @azeier's proposals except for recommended crafts...)

**Comment by azeier** [comment]
After starting to work on this and thinking about the summary stats panels a bit: I don't think we need those.
We have a very powerful filter system, which already includes counts for everything displayed. Instead of displaying "Rare - 76" we can enhance that count to also display the collection count, i.e. "Rare - 17/76".

**Comment by beheh** [comment]
Remaining work:
- [ ] Meta description / Page title with username
- [ ] Add some frontend tests (mostly for filters)
