### ISSUE TITLE
Add monitoring / alerting for InfluxDB data volume size

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#918]
As an operational stakeholder in HSReplay.net, I want to know well in advance when the volume that hosts our InfluxDB database is running out of storage space, so that I can react before InfluxDB (and our Grafana dashboards) become unstable.

Here's a straw man for how we could do this: Install the Telegraf "disk" plugin and have it monitor `/dev/xvdf` on `metrics.hearthsim.net`.

This story is complete when:
- [ ] A graph that displays db mount disk utilization has been added to the "InfluxDB Internals" dashboard in Grafana.
- [ ] An alert has been added to Telegraf that posts a Discord notification when the free space on the db mount drops below 15%.

**Comment by beheh** [comment]
This was marked as done in Jira.
