### ISSUE TITLE
Propose DynamoDB schema for game_replay data

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#919]
As a stakeholder in the data storage infrastructure that backs HSReplay.net, I want to review a proposal for an Amazon DynamoDB table schema suitable for storing game_replay metadata, so that I can plan additional technical work that leverages DynamoDB to provide user-specific reporting (i.e., the new Profiles pages on HSReplay.net) and continued fast random access to individual replays by short id.

This story is complete when we have a design document published to the Infrastructure section of our Confluence wiki that proposes a schema for game replay metadata such that:
- [ ] We have a list of all attributes and types in the table, the partition and sort keys for the table, descriptions of any secondary indexes or other relationships to be created
- [ ] The schema reflects best practices for DynamoDB schema design as described here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices.html
- [ ] The design document includes an explanation / mapping of how the schema would be used to render the artifacts described in the Profiles proposal (https://docs.google.com/document/d/1IijLtoKr_JcloI7d8XqJVLyK5bk6H4EhpVREnagFtvI/edit) - see "Initial Features".
- [ ] The design document includes an explanation / mapping of how the schema would be used to power the existing functionality for replay list and replay details.

**Comment by beheh** [comment]
This was done.
