### ISSUE TITLE
Add premium fallback for ads

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#928]
As a financial stakeholder in HSReplay.net, I would like to see a premium fallback for ads if the ad unit element is not removed by an adblocker (e.g. no adblock but price floor too high).

This story is complete when:
- [x] Ad units for all sizes have the fallback images (https://drive.google.com/drive/u/1/folders/1CEsDYByxoYzKUSFBMifk2wZ66W37XgwR)
- [x] The fallback is either loaded when ad loading fails or from beginning and displayed underneath the ad unit

**Comment by azeier** [comment]
Displaying the ad beneath an unloaded ad does not work. The empty ad prevents the fallback from being clickable. 

The fallback when the nitropay script was blocked is now implemented (behind a feature while i test it), and I followed up with nitropay regarding a callback.

**Comment by beheh** [comment]
Sounds good, a callback is definitely the preferred option here.

**Comment by azeier** [comment]
I'm going to call this complete as described for now. Fallbacks in case of blocked network calls are live now.

I'm still talking to nitropay to figure out what we can do about callbacks but it looks like they currently would replace the adX falback, which is not really what we want. 

A homebrew solution is also not trivial here, as we can't tell whether an ad has been loaded since it all happens in iframes.
