### ISSUE TITLE
Mobile ad placement on HSReplay.net

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#929]
As a financial stakeholder in HSReplay.net, I would like to place ads on the mobile version of HSReplay.net, so that I can begin generating revenue from them.

This story is complete when:
- [x] An administrator can use the Nitropay console to switch on / off the mobile ads listed here: https://drive.google.com/drive/u/1/folders/1sBF8fWqVY4xm7h0zDE7Lj7II2xeDifwF
- [x] There's a behavior we can toggle with a feature tag that replaces a wrapped ad unit with a fake internal mobile ad image that we can use for visual review

**Comment by joolean** [comment]
See the "Meta" page (MetaOverview.tsx) for an example of detecting mobile clients.
