### ISSUE TITLE
Permanent archetype colors

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#932]
As a HearthSim engineer orchestrating clustering and archetype discovery, I would like archetypes to be permanently associated with a single color, so that I can quickly identify existing archetypes while I'm inspecting and merging a new archetype clustering.

This story is complete when:
- [ ] The archetype model in our PostgreSQL database has been extended to include a unique VARCHAR(7) column giving the hexadecimal string encoding of a three-byte color code (e.g., "#233a6e")
- [ ] A color is randomly generated for an archetype at the time it is inserted into the database. (Optional: Constraints on hue, saturation, etc. to produce "nice" colors)
- [ ] The archetype's color is displayed next to its name in the Discover tab on HSReplay.net for both the Live and Latest clusters

**Comment by azeier** [comment]
As the engineer who has been actually doing the clustering for the past couple months, I haven't thought about needing fixed colors even once. I don't think there's a whole lot of value to this.

With archetypes rotating in and out keeping a good color scheme (I.e. distinct colors for all archetypes) for the class will be near to impossible or require a lot of maintenance.

**Comment by joolean** [comment]
Hmmm. I wrote this story from the list of quality-of-life stories you and Andrew came up with. Maybe I misunderstood the intent here...

**Comment by azeier** [comment]
I don't think we talked about this in the last couple months. 

As written (storing color values in postgres) this ticket won't work for the reason I mentioned above. 

If we want to do something like this the colors need be dynamically generated based with archetype names/ids as the seed, but I tried that previously with only mediocre success.

**Comment by beheh** [comment]
I'm guessing this has to do with @amw2104's idea to eventually run an animation showing how "Discover" evolves over time, where archetypes appear, grow, fade out and disappear. We'd need consistent colors to make that work. If that's the case, then this story alone probably doesn't really bring any value and should be prioritized and written together with a story to animate "Discover".
