### ISSUE TITLE
Increase top / popular archetype lists in Partner API classes endpoint to 5

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#935]
As a consumer of class stats from the Partner API, I would like to see more archetypes in the "top performing" and "most popular" archetype lists returned from the "classes" endpoint, so that I can give my users a better idea of how that class is played.

(Microsoft has asked us to bump the number of archetypes in these lists from 3 to 5.)

This story is complete when:
- [x] The "classes" endpoint has been updated to return up to 5 of the top / popular archetypes for a class
- [x] The unit and smoke tests have been updated to cover this change

**Comment by beheh** [comment]
It does not look like we'll need to update the smoke tests:

https://github.com/HearthSim/loadtesting/blob/d991bfaba49056647c5b226f9f941f3509b4b6be/partner_api_tests/test_classes.py#L109-L123
