### ISSUE TITLE
Replay infinitely uploading

### ISSUE THREAD

**Issue by jippiedoe** [HearthSim/HSReplay.net#936]
This replay: 
https://hsreplay.net/uploads/upload/MQoUQyvUE86yFsB2nKEV63/?utm_source=hdt&utm_medium=client&utm_campaign=replay

Is still 'uploading', after more then an hour. It was a 30 turn game with a bunch of shudderwocks, to be fair.

**Comment by beheh** [comment]
Thanks for the report! I attempted to reprocess the replay, but it got stuck again. This is very unusual, but we'll follow up!

**Comment by jleclanche** [comment]
Looks like it's just a really big replay:

8.6M    MQoUQyvUE86yFsB2nKEV63.power.log

I'm guessing the "it's getting stuck" is just that it's hitting the 3 min timeout. It shouldn't really be this inefficient though, might be some good cogs in cleaning that up.

**Comment by jippiedoe** [comment]
Thanks, I figured it was just a really long game with lots of events (I imagine shudderwocks stack up the size quickly, especially when you play two of them a turn). It's a shame, was really interested in the replay

**Comment by jleclanche** [comment]
@jippiedoe Your replay is live, now.

Closing this, we got to the bottom of what's happening and what changed with the patch... improving the exporters/parsers/etc will be another ticket.
