### ISSUE TITLE
Parser Reports Incorrect Spellstone As Player Deck

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#946]
In this game, for example: https://hsreplaynet-replays.s3.amazonaws.com/uploads/2018/08/07/00/34/gqVyoUNAbsPjaV5EoPTEjH.power.log

The deck that gets reported by the parser for the first player is: [[1037,2],[138,2],[43276,2],[43415,1],[46299,1],[46056,2],[531,2],[41243,1],[43122,2],[631,2],[45820,2],[42471,2],[45195,2],[43128,2],[950,2],[48156,1],[993,2]]

However the dbf_id 43276 is for a Greater Spellstone, not the collectible version that was actually in the players deck. The correct deck list would instead show the dbf_id for the base version of the spellstone.

**Comment by beheh** [comment]
Fixed with b8b37d1327e12c5d541df9828350ba6a39407271.
