### ISSUE TITLE
Search/filter by deck code

### ISSUE THREAD

**Issue by KingMob** [HearthSim/HSReplay.net#952]
First, thanks for the great tools!

I was actually a little surprised to see this wasn't here. But basically, if I come across a cool deck suggestion on /r/CompetitiveHS, I'd love to be able to copy the deck code and search/filter for it on HSReplay.net and see how it performs in the hands of those who are already trying it.

I can even submit a PR myself, if you think it's a feature worth having.

Thanks again!

**Comment by beheh** [comment]
Thanks for the suggestion! At least for decks, that's already possible, but it's slightly hidden: On the decks page, scroll down until you see a two text inputs to include/exclude cards. Paste your deck code into the text field to include cards, and you should see the deck list filter to exactly the deck you're looking for.

**Comment by KingMob** [comment]
Oh cool! Any plans to make that feature a bit more visible?

**Comment by beheh** [comment]
We would like to do a generic pass on improving filter usability at some point, but for now unfortunately that feature is contending for screen space with all the other filters, some of which are arguably more important (like Time Range, Game Type and Collection status).
