### ISSUE TITLE
Record replay metadata to DynamoDB

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#960]
As a stakeholder in the production infrastructure of HSReplay.net, I want to begin writing replay metadata into Amazon DynamoDB _in addition to_ PostgreSQL, so that I can begin building up a scalable replay storage layer to support new feature development.

A proposed schema for DynamoDB game replay storage can be found here: https://hearthsim.atlassian.net/wiki/spaces/IN/pages/18612225/DRAFT+Amazon+DynamoDB+schema+for+game+replay

Note that we can't easily guarantee that both the write to PostgreSQL and the write to DynamoDB will succeed. For this reason, we must ensure that the write to PostgreSQL happens first and that the DynamoDB write happens second and only if the first write succeeds. 

Furthermore, failures to write to DynamoDB must not affect the overall success or failure status of the Lambda, and write attempts must generally not impact the overall throughput of upload processing. If you find that a write to DynamoDB inline with normal upload processing introduces too much latency - or that concurrency poses a problem - you might consider enqueueing replays to Kinesis or SQS for out-of-band ingestion.

We should record at least the following metrics related to this change:
- Count of replays written to DynamoDB
- Count of exceptions while writing replays to DynamoDB
  - Count of concurrency throttling exceptions while writing to DynamoDB
- Latency in milliseconds of writing replays to DynamoDB

This story is complete when:
- [ ] A DynamoDB table with the schema above has been provisioned in AWS and added to Terraform
- [ ] A version of the upload processing Lambda function has been deployed to production that writes replays to the target DynamoDB schema _after_ successfully writing them to PostgreSQL has been deployed to production
- [ ] Double-writing to DynamoDB does not substantially increase the latency of the function or otherwise harm the throughput of our upload processing Lambda
- [ ] Panels have been added to the "Lambda" dashboard in Grafana plotting the metrics above
- [ ] A new dashboard "AWS DynamoDB" has been created with panel giving the total item count for the `game_replay` table has been added to it

**Comment by beheh** [comment]
Closed in Jira.
