### ISSUE TITLE
Tool for backfilling replay metadata to DynamoDB

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#961]
As a stakeholder in the infrastructure behind HSReplay.net, I want a tool I can use to backfill historical game replay metadata from the `hsreplaynetdb` PostgreSQL schema to DynamoDB, so that I can make users' replays available to features that interact with DynamoDB and relieve pressure on our RDS cluster.

This tool should support an automated, idempotent, and resumable workflow for transferring data from the `games_gamereplay` table in PostgreSQL to this schema in DynamoDB: https://hearthsim.atlassian.net/wiki/spaces/IN/pages/18612225/DRAFT+Amazon+DynamoDB+schema+for+game+replay. In particular, the tool should support the following use cases:
- Backfilling a time range (in terms of `gamereplay.global_game.match_start`) of replays
- Backfilling a single replay by shortid

It should be possible for a user to specify the write throughput in terms of the number of threads. The tools should use the `BatchWriteItem` method in the DynamoDB API to maximize throughput against the target database. The tool should use a backoff / retry strategy when it encounters throttling as described here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#BatchOperations

The tool should log incremental progress to stderr in terms of highest `match_start` timestamp in batch requests or shortid, to allow it to be restarted on failure.

It should be possible for a user to specify the PostgreSQL source database and target DynamoDB database.

This story is complete when:
- [ ] There is an implementation of this tool that can be run in a virtualenv on a HearthSim developer's desktop that supports the features described above
- [ ] The implementation is documented and covered by unit tests

**Comment by beheh** [comment]
This was done in Jira.
