### ISSUE TITLE
High legend filters on the deck list page

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#964]
As an HSReplay.net Premium user, I want to be able to filter the data on the deck list page to reflect games played by players in the top 1000 "Legend" ranks, so that I can eliminate some of the effects of experimentation by players at the Legend rank floor.

This story is complete when:
- [ ] The RankRange enumeration in `hsredshift.analytics.filters` has been extended to include a new value for `TOP_1000_LEGEND`
- [ ] The "list_decks_by_winrate" and "list_decks_by_opponent_winrate" queries have been extended to filter by `player.legend_rank` when `TOP_1000_LEGEND` filtering is in effect
- [ ] The "Rank Range" filter menu in the left rail menu on the deck list page includes a "Legend (Top 1000)" option, available only to Premium users, its visibility controlled by a feature tag
- [ ] All changes to backend and frontend code is covered by unit or integration tests as appropriate

**Comment by beheh** [comment]
Closed in Jira.
