### ISSUE TITLE
Decks without Mecha'thun being labeled as Mecha'thun Priest

### ISSUE THREAD

**Issue by tiagott-hs** [HearthSim/HSReplay.net#972]
User reported on social media that several Priest decks being labeled as Mecha'thun Priests even though they do not have Mecha'thun in the decklist. Screenshot attached.![mecha'thun priests (?).jpg](https://images.zenhubusercontent.com/5b901e83fb5dec0b0d9ca599/f321535d-a6d3-4fae-a008-af154e08c88b)

**Comment by azeier** [comment]
Added a new archetype for this. Should be fixed.
