### ISSUE TITLE
Warrior decks mislabeled as Mecha'thun Warrior despite Mecha'thun not being on the list

### ISSUE THREAD

**Issue by tiagott-hs** [HearthSim/HSReplay.net#980]
User Aндрюшка Лягушка reported in our Discord that some Warrior decks are being mislabeled as Mecha'thun Warrior despite not including it. Examples:
https://hsreplay.net/decks/GCMQFbnZfgsUdLYd3DSvTf/
https://hsreplay.net/decks/QGu2V2QZEKdoIBFz5FLOBh/

Since this seems to be happening to multiple classes, I wonder if it might be worth adding an extra condition for Mecha'thun decks. UPDATE: 2 other users reported the same thing since I created this ticket on the 8th.

![mechathun warrior mislabeled.png](https://images.zenhubusercontent.com/5b901e83fb5dec0b0d9ca599/3e8875a0-e0e3-45db-8929-f0df26e6b7f6)

**Comment by beheh** [comment]
This specific instance should be fixed. We've got a lead on why this happens, and are following up internally.
