### ISSUE TITLE
Add a setting to disable autoplay

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#99]
This came up on reddit and I think it's a good idea. I started working on it but I need your help @beheh to pass the option down to Joust. I could stuff it into the `<body>` tag but at some point we'll have to figure out a better way to forward these options.

**Comment by beheh** [comment]
The Joust Launcher API supports this, with the [`.startPaused(pause: boolean)`](https://github.com/HearthSim/joust/wiki/Embedding#startpausedpause-boolean) method. Just need to make the JoustEmbedder respect it.
