### ISSUE TITLE
C'thun appearing in game replay after playing Crystal Core

### ISSUE THREAD

**Issue by tiagott-hs** [HearthSim/HSReplay.net#993]
While viewing a replay from one of his games, a customer reported that a random C'thun showed up on the battlefield right after he played Crystal Core. I checked other games and confirmed this seems to be happening pretty consistently. Not sure if only for discounted Crystal Cores or not.

Replay examples:
https://hsreplay.net/replay/e224AavinHyJsY9uB4nGfR#turn=10b
https://hsreplay.net/replay/KUWeaCFTfGpWDv4J7tzhh8#turn=7b

**Comment by beheh** [comment]
Issue moved to [HearthSim/Joust #229](https://github.com/HearthSim/Joust/issues/229) via [**ZenHub**](https://www.zenhub.com/)
